// Weekly special drop fish for the virtual aquarium. 12 freshwater + 12 saltwater showstoppers.
export const FISH_SPECIES_2 = [
  {
    id: 'peacock_gudgeon',
    common: 'Peacock Gudgeon',
    scientific: 'Tateurndina ocellicauda',
    water: 'fresh',
    adultSizeCm: 7,
    bioload: 1,
    minSchool: 2,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.6,
    schooling: 'pair',
    diet: ['pellet', 'frozen'],
    price: 14,
    archetype: 'goby',
    size: 0.6,
    shape: { height: 1.1, finFlow: 1.1 },
    colors: {
      base: '#5a8ac8',
      belly: '#e8c84a',
      fin: '#e8b040',
      pattern: 'spots',
      patternColor: '#d04040',
      patternScale: 1.1,
      iridescence: 0.6
    },
    habitat: 'Slow rainforest streams and ponds of eastern Papua New Guinea.',
    facts: [
      'A big black spot at the base of its tail looks like a peacock feather eye and fools predators.',
      'Grown-up males get a bumpy round forehead, like they are wearing a helmet.',
      'The dad hides the eggs in a little cave and fans them with his fins until they hatch.'
    ],
    care: 'Easy'
  },
  {
    id: 'gardneri_killifish',
    common: 'Gardneri Killifish',
    scientific: 'Fundulopanchax gardneri',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 1,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'top',
    speed: 0.8,
    schooling: 'pair',
    diet: ['flake', 'frozen'],
    price: 12,
    archetype: 'torpedo',
    size: 0.75,
    shape: { height: 1.0, finFlow: 1.2 },
    colors: {
      base: '#3aa8a0',
      belly: '#7ac8b0',
      fin: '#e8c830',
      pattern: 'spots',
      patternColor: '#d03030',
      patternScale: 1.2,
      iridescence: 0.7
    },
    habitat: 'Shallow swamps, puddles, and forest streams of Nigeria and Cameroon in West Africa.',
    facts: [
      'Its eggs can rest in damp mud for weeks and hatch when the rains fill the puddles again.',
      'Males shimmer blue-green with red freckles and sunshine-yellow fin edges.',
      'It is an amazing jumper that can leap out of a bowl, so its tank needs a lid.'
    ],
    care: 'Easy'
  },
  {
    id: 'elephant_nose_fish',
    common: 'Elephant Nose Fish',
    scientific: 'Gnathonemus petersii',
    water: 'fresh',
    adultSizeCm: 23,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal', 'expertDiet'],
    zone: 'bottom',
    speed: 0.6,
    schooling: 'solo',
    diet: ['frozen'],
    price: 30,
    archetype: 'loach',
    size: 1.2,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#2a2a2e',
      belly: '#3a3a3e',
      fin: '#2a2a2e',
      pattern: 'stripesV',
      patternColor: '#c8c8c0',
      patternScale: 0.6,
      iridescence: 0.1
    },
    habitat: 'Muddy, slow-moving rivers of West and Central Africa.',
    facts: [
      'Its trunk is really a long wiggly chin that it uses to feel for worms in the mud.',
      'It makes tiny pulses of electricity to find its way in water too dark to see.',
      'For its size it has one of the biggest brains of any fish in the world.'
    ],
    care: 'Hard'
  },
  {
    id: 'black_ghost_knife',
    common: 'Black Ghost Knifefish',
    scientific: 'Apteronotus albifrons',
    water: 'fresh',
    adultSizeCm: 40,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.7,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 30,
    archetype: 'eel',
    size: 1.5,
    shape: { height: 1.2, finFlow: 1.2 },
    colors: {
      base: '#141418',
      belly: '#1c1c20',
      fin: '#101014',
      pattern: 'stripesV',
      patternColor: '#e8e8e4',
      patternScale: 0.5,
      iridescence: 0.1
    },
    habitat: 'Sandy, fast-flowing rivers of the Amazon basin in South America.',
    facts: [
      'It swims by rippling one long ribbon fin, so it can glide backward as easily as forward.',
      'It "sees" in total darkness by making a gentle electric field around its body.',
      'Old legends from the Amazon say the spirits of ancestors ride inside these ghostly fish.'
    ],
    care: 'Medium'
  },
  {
    id: 'ropefish',
    common: 'Ropefish',
    scientific: 'Erpetoichthys calabaricus',
    water: 'fresh',
    adultSizeCm: 38,
    bioload: 8,
    minSchool: 2,
    temperament: 'peaceful',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal', 'jumper'],
    zone: 'bottom',
    speed: 0.5,
    schooling: 'loose',
    diet: ['frozen', 'pellet'],
    price: 25,
    archetype: 'eel',
    size: 1.6,
    colors: {
      base: '#6a7a4a',
      belly: '#d8cc98',
      fin: '#6a7a4a',
      pattern: 'none',
      patternColor: '#4a5a34',
      patternScale: 1.0,
      iridescence: 0.15
    },
    habitat: 'Slow, weedy rivers and swamps of Nigeria and Cameroon in West Africa.',
    facts: [
      'It has lungs as well as gills and swims up to gulp real air.',
      'On rainy nights it can wriggle over land like a snake to reach a new pool.',
      'Its body is covered in hard diamond-shaped scales, like a suit of chain mail.'
    ],
    care: 'Medium'
  },
  {
    id: 'clouded_archerfish',
    common: 'Clouded Archerfish',
    scientific: 'Toxotes blythii',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 3,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'top',
    speed: 0.9,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 40,
    archetype: 'torpedo',
    size: 1.1,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#c8b878',
      belly: '#e8dcb0',
      fin: '#b8a868',
      pattern: 'stripesV',
      patternColor: '#1a1a1a',
      patternScale: 0.8,
      iridescence: 0.3
    },
    habitat: 'Rivers of Myanmar in Southeast Asia, far from the sea unlike most archerfish.',
    facts: [
      'It spits a jet of water like a squirt gun to knock bugs off branches into the water.',
      'Its aim is amazing — it even corrects for how light bends at the surface.',
      'If spitting fails, it can leap right out of the water to grab its snack.'
    ],
    care: 'Medium'
  },
  {
    id: 'gold_nugget_pleco',
    common: 'Gold Nugget Pleco',
    scientific: 'Baryancistrus xanthellus',
    water: 'fresh',
    adultSizeCm: 24,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['algae', 'pellet'],
    price: 40,
    archetype: 'pleco',
    size: 1.2,
    colors: {
      base: '#2a2418',
      belly: '#4a3c24',
      fin: '#e8b820',
      pattern: 'spots',
      patternColor: '#f0c020',
      patternScale: 1.2,
      iridescence: 0.1
    },
    habitat: 'Rocky rapids of the Rio Xingu, a fast clearwater river in Brazil.',
    facts: [
      'It is midnight black dusted with golden polka dots, like a starry night sky.',
      'Its fins are trimmed with a bright gold band, as if dipped in paint.',
      'New plecos get secret codes like L018 before scientists give them real names.'
    ],
    care: 'Medium'
  },
  {
    id: 'zebra_pleco',
    common: 'Zebra Pleco',
    scientific: 'Hypancistrus zebra',
    water: 'fresh',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 45,
    archetype: 'pleco',
    size: 0.7,
    colors: {
      base: '#f0f0ec',
      belly: '#f8f8f4',
      fin: '#e8e8e4',
      pattern: 'stripesH',
      patternColor: '#141414',
      patternScale: 1.0,
      iridescence: 0.1
    },
    habitat: 'Deep, fast rocky channels of the Rio Xingu in Brazil — and nowhere else on Earth.',
    facts: [
      'Its crisp black and white stripes make it look like a tiny swimming zebra.',
      'It is one of the rarest aquarium fish, so hobby breeders raise babies to protect it.',
      'Unlike most plecos it skips the algae and prefers meaty food like worms.'
    ],
    care: 'Hard'
  },
  {
    id: 'amazon_puffer',
    common: 'Amazon Puffer',
    scientific: 'Colomesus asellus',
    water: 'fresh',
    adultSizeCm: 8,
    bioload: 4,
    minSchool: 3,
    temperament: 'semi',
    predator: false,
    finNipper: true,
    longFins: false,
    tags: [],
    zone: 'all',
    speed: 0.9,
    schooling: 'loose',
    diet: ['frozen', 'pellet'],
    price: 20,
    archetype: 'puffer',
    size: 0.7,
    colors: {
      base: '#a8b048',
      belly: '#f0ead0',
      fin: '#c8c880',
      pattern: 'stripesV',
      patternColor: '#2a3020',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Big open rivers of the Amazon basin, swimming in groups unlike most puffers.',
    facts: [
      'When scared it gulps water and puffs up into a little round ball.',
      'Its beak-like teeth never stop growing, so it crunches snails to keep them short.',
      'It is one of the only puffers that travels the river in friendly schools.'
    ],
    care: 'Medium'
  },
  {
    id: 'leopard_bush_fish',
    common: 'Leopard Bush Fish',
    scientific: 'Ctenopoma acutirostre',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'mid',
    speed: 0.4,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 18,
    archetype: 'cichlid',
    size: 1.0,
    shape: { height: 1.2, finFlow: 1.0 },
    colors: {
      base: '#c8a04a',
      belly: '#d8b86a',
      fin: '#b89040',
      pattern: 'spots',
      patternColor: '#3a2a14',
      patternScale: 1.2,
      iridescence: 0.1
    },
    habitat: 'Slow, shady waters of the Congo River basin in central Africa.',
    facts: [
      'It drifts sideways pretending to be a dead leaf, then slurps up food that swims too close.',
      'Its leopard spots hide it perfectly among sunken leaves and roots.',
      'Like a betta, it can gulp air from the surface with a special breathing organ.'
    ],
    care: 'Medium'
  },
  {
    id: 'scarlet_badis',
    common: 'Scarlet Badis',
    scientific: 'Dario dario',
    water: 'fresh',
    adultSizeCm: 2,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['expertDiet'],
    zone: 'bottom',
    speed: 0.5,
    schooling: 'solo',
    diet: ['frozen'],
    price: 10,
    archetype: 'cichlid',
    size: 0.6,
    colors: {
      base: '#e04028',
      belly: '#f0e8d8',
      fin: '#d83820',
      pattern: 'stripesV',
      patternColor: '#7ac8e8',
      patternScale: 1.0,
      iridescence: 0.5
    },
    habitat: 'Shallow, plant-choked streams of the Brahmaputra River in India.',
    facts: [
      'It is one of the smallest perch-like fish on Earth — smaller than a thumbnail.',
      'Males wear candy-cane stripes of ruby red and shiny silver-blue.',
      'A male picks a tiny plant patch as his castle and dances sideways to show it off.'
    ],
    care: 'Medium'
  },
  {
    id: 'electric_blue_hap',
    common: 'Electric Blue Hap',
    scientific: 'Sciaenochromis fryeri',
    water: 'fresh',
    adultSizeCm: 16,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'solo',
    diet: ['pellet', 'frozen'],
    price: 22,
    archetype: 'cichlid',
    size: 1.3,
    colors: {
      base: '#2a6ae0',
      belly: '#4a86e8',
      fin: '#2456c8',
      pattern: 'stripesV',
      patternColor: '#1a3a88',
      patternScale: 0.9,
      iridescence: 0.8
    },
    habitat: 'Rocky shores of Lake Malawi in East Africa.',
    facts: [
      'Grown-up males glow electric blue, like a flash of lightning underwater.',
      'The mom carries her eggs and wiggly babies safely inside her mouth.',
      'Its home, Lake Malawi, has more kinds of fish than any other lake on Earth.'
    ],
    care: 'Medium'
  },
  {
    id: 'moorish_idol',
    common: 'Moorish Idol',
    scientific: 'Zanclus cornutus',
    water: 'salt',
    adultSizeCm: 21,
    bioload: 8,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: true,
    tags: ['expertDiet'],
    zone: 'mid',
    speed: 0.9,
    schooling: 'solo',
    diet: ['frozen'],
    price: 45,
    archetype: 'tang',
    size: 1.1,
    shape: { height: 1.5, finFlow: 1.4 },
    colors: {
      base: '#f0ead2',
      belly: '#f8f4e4',
      fin: '#f0c828',
      pattern: 'stripesV',
      patternColor: '#16161a',
      patternScale: 0.8,
      iridescence: 0.2
    },
    habitat: 'Coral reefs across the Indian and Pacific Oceans, one of the widest homes of any reef fish.',
    facts: [
      'A long white streamer trails from its back fin like a knight\'s banner.',
      'Gill, the wise leader fish in Finding Nemo, is a Moorish idol.',
      'In the wild it nibbles sponges, a strange snack most fish will not touch.'
    ],
    care: 'Hard'
  },
  {
    id: 'achilles_tang',
    common: 'Achilles Tang',
    scientific: 'Acanthurus achilles',
    water: 'salt',
    adultSizeCm: 24,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.2,
    schooling: 'solo',
    diet: ['algae', 'frozen'],
    price: 45,
    archetype: 'tang',
    size: 1.05,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#1a1a1e',
      belly: '#26262a',
      fin: '#f05a1a',
      pattern: 'spots',
      patternColor: '#f05a1a',
      patternScale: 0.6,
      iridescence: 0.3
    },
    habitat: 'Wave-pounded surge zones of Hawaii and the central Pacific.',
    facts: [
      'It lives right where the waves crash hardest, surfing the white water like a pro.',
      'The bright orange teardrop near its tail marks where its sharp tail blade hides.',
      'It is named after Achilles, a famous hero from ancient Greek stories.'
    ],
    care: 'Hard'
  },
  {
    id: 'picasso_triggerfish',
    common: 'Picasso Triggerfish',
    scientific: 'Rhinecanthus aculeatus',
    water: 'salt',
    adultSizeCm: 25,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'all',
    speed: 0.9,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 40,
    archetype: 'tang',
    size: 1.1,
    shape: { height: 1.2, finFlow: 1.0 },
    colors: {
      base: '#d8cca8',
      belly: '#f0ead0',
      fin: '#c8bc98',
      pattern: 'stripesV',
      patternColor: '#2a4a8a',
      patternScale: 0.7,
      iridescence: 0.2
    },
    habitat: 'Shallow reef flats and lagoons of the Indo-Pacific.',
    facts: [
      'In Hawaii it is called humuhumunukunukuapua\'a — one of the longest fish names in the world.',
      'At bedtime it wedges into a rock crack and locks itself in with a trigger spine on its back.',
      'When caught it grunts like a little pig, which is what its Hawaiian name means.'
    ],
    care: 'Medium'
  },
  {
    id: 'snowflake_eel',
    common: 'Snowflake Eel',
    scientific: 'Echidna nebulosa',
    water: 'salt',
    adultSizeCm: 60,
    bioload: 14,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal', 'jumper'],
    zone: 'bottom',
    speed: 0.5,
    schooling: 'solo',
    diet: ['frozen'],
    price: 35,
    archetype: 'eel',
    size: 1.6,
    colors: {
      base: '#e8e0c8',
      belly: '#f0ead8',
      fin: '#d8d0b8',
      pattern: 'spots',
      patternColor: '#2a2a24',
      patternScale: 1.3,
      iridescence: 0.1
    },
    habitat: 'Rocky crevices and reef flats of the Indo-Pacific from Africa to Hawaii.',
    facts: [
      'Instead of sharp fangs it has pebble-like teeth for crunching crabs.',
      'It opens and closes its mouth to breathe — it is pumping water, not being grumpy.',
      'It is a famous escape artist that can squeeze through tiny gaps, so its tank needs a tight lid.'
    ],
    care: 'Medium'
  },
  {
    id: 'ribbon_eel',
    common: 'Ribbon Eel',
    scientific: 'Rhinomuraena quaesita',
    water: 'salt',
    adultSizeCm: 100,
    bioload: 8,
    minSchool: 1,
    temperament: 'peaceful',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['expertDiet', 'jumper'],
    zone: 'bottom',
    speed: 0.4,
    schooling: 'solo',
    diet: ['frozen'],
    price: 45,
    archetype: 'eel',
    size: 1.4,
    colors: {
      base: '#1a4ae0',
      belly: '#2a5ae8',
      fin: '#f0d020',
      pattern: 'none',
      patternColor: '#f0d020',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Sandy burrows on reef slopes and lagoons of the Indo-Pacific.',
    facts: [
      'It starts life black, turns electric blue and yellow as a male, and can later turn yellow and become a mom.',
      'Its nostrils flare open like tiny trumpets to smell the water.',
      'It hides in a burrow with just its head out, swaying like a ribbon in the breeze.'
    ],
    care: 'Hard'
  },
  {
    id: 'leaf_scorpionfish',
    common: 'Leaf Scorpionfish',
    scientific: 'Taenianotus triacanthus',
    water: 'salt',
    adultSizeCm: 10,
    bioload: 4,
    minSchool: 1,
    temperament: 'peaceful',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['expertDiet'],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['frozen'],
    price: 35,
    archetype: 'lionfish',
    size: 0.8,
    shape: { height: 1.2, finFlow: 1.1 },
    colors: {
      base: '#e8c838',
      belly: '#f0d868',
      fin: '#d8b828',
      pattern: 'none',
      patternColor: '#c8a820',
      patternScale: 1.0,
      iridescence: 0.1
    },
    habitat: 'Coral heads and rubble patches of Indo-Pacific reefs.',
    facts: [
      'It rocks gently side to side, pretending to be a fallen leaf drifting in the current.',
      'Every couple of weeks it sheds its whole outer skin, like taking off a costume.',
      'Leaf scorpionfish come in yellow, pink, brown, or white — each one picks its own disguise.'
    ],
    care: 'Medium'
  },
  {
    id: 'squarespot_anthias',
    common: 'Squarespot Anthias',
    scientific: 'Pseudanthias pleurotaenia',
    water: 'salt',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.1,
    schooling: 'loose',
    diet: ['frozen', 'pellet'],
    price: 40,
    archetype: 'cichlid',
    size: 0.9,
    shape: { height: 1.1, finFlow: 1.2 },
    colors: {
      base: '#e83a8a',
      belly: '#f06aa8',
      fin: '#d82a7a',
      pattern: 'spots',
      patternColor: '#f8c8e8',
      patternScale: 0.6,
      iridescence: 0.5
    },
    habitat: 'Deep reef walls and drop-offs of the western Pacific.',
    facts: [
      'Males have a glowing pale square on each side that looks lit up from the inside.',
      'If the group needs a new leader, the biggest female changes into a hot-pink male.',
      'It lives deeper on the reef than most anthias, where the water glows twilight blue.'
    ],
    care: 'Medium'
  },
  {
    id: 'mccosker_flasher_wrasse',
    common: "McCosker's Flasher Wrasse",
    scientific: 'Paracheilinus mccoskeri',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: true,
    tags: ['jumper'],
    zone: 'mid',
    speed: 1.3,
    schooling: 'loose',
    diet: ['frozen', 'pellet', 'flake'],
    price: 30,
    archetype: 'torpedo',
    size: 0.65,
    shape: { height: 0.9, finFlow: 1.3 },
    colors: {
      base: '#e05838',
      belly: '#f0a868',
      fin: '#e83048',
      pattern: 'stripesH',
      patternColor: '#38b8e8',
      patternScale: 1.2,
      iridescence: 0.8
    },
    habitat: 'Rubble slopes of the Indian Ocean from East Africa to Indonesia.',
    facts: [
      'At sunset the male does a flash dance, turbo-boosting his colors to glowing neon.',
      'During the show he pops his fins up like sails and zooms in loops.',
      'He is so gentle that even tiny shrimp are safe swimming beside him.'
    ],
    care: 'Easy'
  },
  {
    id: 'porcupine_puffer',
    common: 'Porcupine Puffer',
    scientific: 'Diodon holocanthus',
    water: 'salt',
    adultSizeCm: 30,
    bioload: 14,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'all',
    speed: 0.6,
    schooling: 'solo',
    diet: ['frozen'],
    price: 40,
    archetype: 'puffer',
    size: 1.4,
    colors: {
      base: '#c8a868',
      belly: '#f0e8d0',
      fin: '#c8b078',
      pattern: 'spots',
      patternColor: '#3a3020',
      patternScale: 1.0,
      iridescence: 0.1
    },
    habitat: 'Warm lagoons and coastal reefs in tropical seas all around the world.',
    facts: [
      'When scared it gulps water and blows up into a balloon covered in pointy spikes.',
      'It has big puppy-dog eyes and learns to recognize its keeper, begging at the glass.',
      'Its teeth are fused into a beak strong enough to crack crab and snail shells.'
    ],
    care: 'Medium'
  },
  {
    id: 'matted_filefish',
    common: 'Matted Filefish',
    scientific: 'Acreichthys tomentosus',
    water: 'salt',
    adultSizeCm: 9,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.5,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 25,
    archetype: 'tang',
    size: 0.8,
    shape: { height: 1.2, finFlow: 1.0 },
    colors: {
      base: '#8a9a6a',
      belly: '#a8b088',
      fin: '#7a8a5a',
      pattern: 'spots',
      patternColor: '#4a5438',
      patternScale: 1.4,
      iridescence: 0.05
    },
    habitat: 'Seagrass beds and shallow lagoons of the Indo-Pacific.',
    facts: [
      'It changes color and grows shaggy skin tufts to vanish into the seagrass.',
      'Reef keepers love it because it gobbles up pest anemones that sting corals.',
      'The spine on its head locks straight up like a flag, so predators cannot pull it from cracks.'
    ],
    care: 'Easy'
  },
  {
    id: 'royal_angelfish',
    common: 'Royal Angelfish',
    scientific: 'Pygoplites diacanthus',
    water: 'salt',
    adultSizeCm: 25,
    bioload: 8,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly', 'expertDiet'],
    zone: 'mid',
    speed: 0.8,
    schooling: 'solo',
    diet: ['frozen'],
    price: 45,
    archetype: 'tang',
    size: 1.05,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#f08828',
      belly: '#f0a848',
      fin: '#4a3ac0',
      pattern: 'stripesV',
      patternColor: '#e8ecf4',
      patternScale: 0.9,
      iridescence: 0.4
    },
    habitat: 'Coral-rich lagoons and reef slopes of the Indo-Pacific and Red Sea.',
    facts: [
      'It looks hand-painted, with blue-edged white stripes swooping over bright orange.',
      'It is a royal picky eater — in the wild it dines mostly on sponges.',
      'It never strays far from a cave and slips sideways into cracks when startled.'
    ],
    care: 'Hard'
  },
  {
    id: 'harlequin_tuskfish',
    common: 'Harlequin Tuskfish',
    scientific: 'Choerodon fasciatus',
    water: 'salt',
    adultSizeCm: 25,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.8,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 42,
    archetype: 'torpedo',
    size: 1.2,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#f0e8dc',
      belly: '#f6f0e6',
      fin: '#e05828',
      pattern: 'stripesV',
      patternColor: '#e05828',
      patternScale: 0.9,
      iridescence: 0.3
    },
    habitat: 'Reef edges of the Great Barrier Reef and the western Pacific.',
    facts: [
      'It has bright BLUE teeth that poke out like little tusks.',
      'It uses those tusks to pry crabs and snails out of the rocks for dinner.',
      'Each of its orange stripes is outlined in glowing electric blue.'
    ],
    care: 'Medium'
  }
];
