export const FRESHWATER_SPECIES = [
  {
    id: 'neon_tetra',
    common: 'Neon Tetra',
    scientific: 'Paracheirodon innesi',
    water: 'fresh',
    adultSizeCm: 3,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 3,
    archetype: 'torpedo',
    size: 0.8,
    colors: {
      base: '#4aa8d8',
      belly: '#e0524a',
      fin: '#cfe8f0',
      pattern: 'lateralStripe',
      patternColor: '#33ccff',
      patternScale: 1.0,
      iridescence: 0.9
    },
    habitat: 'Blackwater streams of the Amazon basin in South America.',
    facts: [
      'Its glowing blue stripe helps the school stay together in dark water.',
      'A group of neon tetras all turn at the same moment, like magic.',
      'At night its bright colors fade so predators cannot see it sleeping.'
    ],
    care: 'Easy'
  },
  {
    id: 'cardinal_tetra',
    common: 'Cardinal Tetra',
    scientific: 'Paracheirodon axelrodi',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 5,
    archetype: 'torpedo',
    size: 0.85,
    colors: {
      base: '#d0202a',
      belly: '#c02028',
      fin: '#e8d8d8',
      pattern: 'lateralStripe',
      patternColor: '#22aaee',
      patternScale: 1.0,
      iridescence: 0.9
    },
    habitat: 'Tea-colored blackwater tributaries of the Rio Negro and Orinoco rivers in South America.',
    facts: [
      'Its red stripe runs the whole length of its body, even more red than a neon tetra.',
      'In the wild it lives in water the color of tea, stained by fallen leaves.',
      'Thousands of cardinal tetras can swim together in one giant wild school.'
    ],
    care: 'Easy'
  },
  {
    id: 'guppy',
    common: 'Guppy',
    scientific: 'Poecilia reticulata',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 2,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: true,
    tags: [],
    zone: 'top',
    speed: 1.0,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'livebearer',
    size: 0.8,
    shape: { height: 1.0, finFlow: 1.4 },
    colors: {
      base: '#9aa8b0',
      belly: '#d8dcd8',
      fin: '#e86028',
      pattern: 'gradientTail',
      patternColor: '#e83050',
      patternScale: 1.2,
      iridescence: 0.7
    },
    habitat: 'Warm streams, ditches, and ponds of Trinidad and northern South America.',
    facts: [
      'Guppies do not lay eggs — the babies are born already swimming.',
      'Every male guppy has his own one-of-a-kind tail pattern, like a fingerprint.',
      'Wild guppies help people by eating mosquito babies in ponds.'
    ],
    care: 'Easy'
  },
  {
    id: 'betta',
    common: 'Betta (Siamese Fighting Fish)',
    scientific: 'Betta splendens',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 2,
    minSchool: 1,
    temperament: 'aggressive',
    predator: false,
    finNipper: false,
    longFins: true,
    tags: ['soloOnly'],
    zone: 'top',
    speed: 0.5,
    schooling: 'solo',
    diet: ['pellet', 'frozen'],
    price: 8,
    archetype: 'betta',
    size: 1.0,
    shape: { height: 1.0, finFlow: 1.6 },
    colors: {
      base: '#2038c8',
      belly: '#1a2ba0',
      fin: '#c02040',
      pattern: 'none',
      patternColor: '#7040c0',
      patternScale: 1.0,
      iridescence: 0.7
    },
    habitat: 'Shallow rice paddies, marshes, and slow ditches of Thailand and Southeast Asia.',
    facts: [
      'A betta can gulp air from the surface using a special organ called a labyrinth.',
      'Dads build a floating nest out of bubbles and guard the eggs inside it.',
      'Two male bettas will fight, so each betta must be the only betta in the tank.'
    ],
    care: 'Easy'
  },
  {
    id: 'angelfish',
    common: 'Angelfish',
    scientific: 'Pterophyllum scalare',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: true,
    tags: [],
    zone: 'mid',
    speed: 0.6,
    schooling: 'loose',
    diet: ['flake', 'pellet', 'frozen'],
    price: 12,
    archetype: 'angelfish',
    size: 1.0,
    shape: { height: 1.0, finFlow: 1.3 },
    colors: {
      base: '#c9ccc9',
      belly: '#d8dcd8',
      fin: '#b8bcb8',
      pattern: 'stripesV',
      patternColor: '#1a1a1a',
      patternScale: 0.8,
      iridescence: 0.4
    },
    habitat: 'Slow, plant-filled rivers and flooded forests of the Amazon basin.',
    facts: [
      'Its tall, thin body lets it slip sideways between underwater plant stems.',
      'Its dark stripes work like camouflage among plant roots and shadows.',
      'Angelfish parents guard their eggs and fan them with their fins to keep them clean.'
    ],
    care: 'Medium'
  },
  {
    id: 'discus',
    common: 'Discus',
    scientific: 'Symphysodon aequifasciatus',
    water: 'fresh',
    adultSizeCm: 18,
    bioload: 6,
    minSchool: 5,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.5,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 60,
    archetype: 'discus',
    size: 1.0,
    colors: {
      base: '#3fa8a0',
      belly: '#4ab0a8',
      fin: '#b04030',
      pattern: 'stripesH',
      patternColor: '#c04030',
      patternScale: 0.7,
      iridescence: 0.5
    },
    habitat: 'Calm, warm blackwater lakes and flooded forests of the Amazon River.',
    facts: [
      'It is shaped like a round dinner plate, which is how it got its name.',
      'Baby discus eat a special slime that grows on their parents\' skin.',
      'Discus talk to each other by changing how dark their stripes look.'
    ],
    care: 'Hard'
  },
  {
    id: 'bronze_corydoras',
    common: 'Bronze Corydoras',
    scientific: 'Corydoras aeneus',
    water: 'fresh',
    adultSizeCm: 7,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.7,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 5,
    archetype: 'cory',
    size: 1.0,
    colors: {
      base: '#8a9a6a',
      belly: '#d8ceb0',
      fin: '#b8b898',
      pattern: 'none',
      patternColor: '#5a6a4a',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Sandy-bottomed streams and quiet river edges across much of South America.',
    facts: [
      'It wears bony armor plates instead of normal scales.',
      'Its whisker-like barbels help it feel for food hidden in the sand.',
      'Sometimes it dashes up to gulp a bubble of air, then zooms back down.'
    ],
    care: 'Easy'
  },
  {
    id: 'panda_corydoras',
    common: 'Panda Corydoras',
    scientific: 'Corydoras panda',
    water: 'fresh',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.7,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 8,
    archetype: 'cory',
    size: 0.8,
    colors: {
      base: '#e8dcc0',
      belly: '#f0e8d0',
      fin: '#d8ceb0',
      pattern: 'patches',
      patternColor: '#1e1e1e',
      patternScale: 1.2,
      iridescence: 0.2
    },
    habitat: 'Cool, clear mountain streams in the foothills of the Peruvian Andes.',
    facts: [
      'It has black eye patches just like a panda bear.',
      'Wild panda corys live in chilly streams fed by melting mountain snow.',
      'It rests its body on the sand and props itself up on its front fins.'
    ],
    care: 'Easy'
  },
  {
    id: 'sterbai_corydoras',
    common: 'Sterbai Corydoras',
    scientific: 'Corydoras sterbai',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.7,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 10,
    archetype: 'cory',
    size: 0.9,
    colors: {
      base: '#4a4038',
      belly: '#d8c8a8',
      fin: '#e8a030',
      pattern: 'spots',
      patternColor: '#e8dcc0',
      patternScale: 1.4,
      iridescence: 0.2
    },
    habitat: 'Warm rivers of the Guaporé region between Brazil and Bolivia.',
    facts: [
      'It is covered in rows of tiny white polka dots.',
      'Its front fins have a bright orange stripe, like it is wearing gloves.',
      'It loves warmer water than most corys, so it can live with discus.'
    ],
    care: 'Easy'
  },
  {
    id: 'bristlenose_pleco',
    common: 'Bristlenose Pleco',
    scientific: 'Ancistrus cirrhosus',
    water: 'fresh',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.4,
    schooling: 'solo',
    diet: ['algae', 'pellet'],
    price: 9,
    archetype: 'pleco',
    size: 1.0,
    colors: {
      base: '#4a4032',
      belly: '#8a7a5a',
      fin: '#4a4032',
      pattern: 'spots',
      patternColor: '#d0c090',
      patternScale: 1.3,
      iridescence: 0.1
    },
    habitat: 'Fast-flowing rivers and streams of the Amazon basin in South America.',
    facts: [
      'Grown-up males grow funny wiggly bristles all over their noses.',
      'Its mouth is a suction cup that scrapes algae off rocks and glass.',
      'Dad plecos hide in a cave and babysit the eggs until they hatch.'
    ],
    care: 'Easy'
  },
  {
    id: 'fancy_goldfish',
    common: 'Fancy Goldfish (Oranda)',
    scientific: 'Carassius auratus',
    water: 'fresh',
    adultSizeCm: 18,
    bioload: 8,
    minSchool: 2,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: true,
    tags: ['coldwater'],
    zone: 'all',
    speed: 0.5,
    schooling: 'loose',
    diet: ['flake', 'pellet'],
    price: 15,
    archetype: 'goldfish',
    size: 1.1,
    shape: { height: 1.1, finFlow: 1.4 },
    colors: {
      base: '#f08020',
      belly: '#f8c060',
      fin: '#f09030',
      pattern: 'none',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.5
    },
    habitat: 'Bred from wild carp that live in cool, slow rivers and ponds of East Asia.',
    facts: [
      'Goldfish were first kept by people in China more than a thousand years ago.',
      'It has no stomach, so it likes lots of tiny meals instead of one big one.',
      'Goldfish can see more colors than people can, including ultraviolet light.'
    ],
    care: 'Easy'
  },
  {
    id: 'kuhli_loach',
    common: 'Kuhli Loach',
    scientific: 'Pangio kuhlii',
    water: 'fresh',
    adultSizeCm: 10,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.6,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 5,
    archetype: 'eel',
    size: 1.0,
    colors: {
      base: '#e8a040',
      belly: '#f0d0a0',
      fin: '#d89838',
      pattern: 'stripesV',
      patternColor: '#3a281a',
      patternScale: 1.1,
      iridescence: 0.1
    },
    habitat: 'Soft, leafy stream bottoms in the forests of Indonesia and Malaysia.',
    facts: [
      'It looks like a tiny striped noodle and loves to wiggle under things.',
      'It can bury itself in soft sand with just its face peeking out.',
      'It is shy in the day but comes out to explore when the lights go off.'
    ],
    care: 'Easy'
  },
  {
    id: 'dwarf_gourami',
    common: 'Dwarf Gourami',
    scientific: 'Trichogaster lalius',
    water: 'fresh',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'top',
    speed: 0.6,
    schooling: 'solo',
    diet: ['flake', 'frozen'],
    price: 8,
    archetype: 'gourami',
    size: 0.8,
    colors: {
      base: '#e05030',
      belly: '#e87040',
      fin: '#d84828',
      pattern: 'stripesV',
      patternColor: '#40b0e0',
      patternScale: 1.2,
      iridescence: 0.7
    },
    habitat: 'Slow, weedy waters and rice paddies of India and Bangladesh.',
    facts: [
      'It breathes air at the surface with a special lung-like organ.',
      'Its long thread fins work like fingers to feel the world around it.',
      'Males glue a bubble nest together at the surface using plant bits and spit.'
    ],
    care: 'Medium'
  },
  {
    id: 'german_blue_ram',
    common: 'German Blue Ram',
    scientific: 'Mikrogeophagus ramirezi',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.6,
    schooling: 'pair',
    diet: ['pellet', 'frozen'],
    price: 12,
    archetype: 'cichlid',
    size: 0.8,
    colors: {
      base: '#d8b840',
      belly: '#e0508a',
      fin: '#e8c850',
      pattern: 'spots',
      patternColor: '#55aaff',
      patternScale: 1.3,
      iridescence: 0.8
    },
    habitat: 'Warm, shallow pools and slow streams of the Orinoco River savanna in Venezuela and Colombia.',
    facts: [
      'Its body sparkles with glittery blue spots, like it is covered in sequins.',
      'Mom and dad rams take turns guarding their eggs together.',
      'It sifts mouthfuls of sand and spits it out to find hidden snacks.'
    ],
    care: 'Hard'
  },
  {
    id: 'tiger_barb',
    common: 'Tiger Barb',
    scientific: 'Puntigrus tetrazona',
    water: 'fresh',
    adultSizeCm: 7,
    bioload: 2,
    minSchool: 8,
    temperament: 'semi',
    predator: false,
    finNipper: true,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.3,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.9,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#e8a030',
      belly: '#f0c878',
      fin: '#e04020',
      pattern: 'stripesV',
      patternColor: '#1a1a1a',
      patternScale: 0.9,
      iridescence: 0.3
    },
    habitat: 'Clear, swift forest streams of Sumatra and Borneo in Southeast Asia.',
    facts: [
      'It wears four bold black stripes, just like a tiny tiger.',
      'Tiger barbs play chase games with each other all day long.',
      'In a big group they chase each other; in a small group they pester other fish, so they need lots of friends.'
    ],
    care: 'Easy'
  },
  {
    id: 'zebra_danio',
    common: 'Zebra Danio',
    scientific: 'Danio rerio',
    water: 'fresh',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'top',
    speed: 1.6,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 3,
    archetype: 'torpedo',
    size: 0.85,
    colors: {
      base: '#c8d0d8',
      belly: '#e8ecf0',
      fin: '#b8c0d0',
      pattern: 'stripesH',
      patternColor: '#2a3a6a',
      patternScale: 1.0,
      iridescence: 0.6
    },
    habitat: 'Cool streams, ponds, and rice paddies of India and Bangladesh.',
    facts: [
      'It zooms around all day and almost never stops to rest.',
      'Its racing stripes run head to tail, like a tiny striped rocket.',
      'Scientists love zebra danios because their eggs are clear like glass.'
    ],
    care: 'Easy'
  },
  {
    id: 'harlequin_rasbora',
    common: 'Harlequin Rasbora',
    scientific: 'Trigonostigma heteromorpha',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 8,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.75,
    shape: { height: 1.2, finFlow: 1.0 },
    colors: {
      base: '#e8875a',
      belly: '#f0b088',
      fin: '#e07848',
      pattern: 'patches',
      patternColor: '#1a1a2a',
      patternScale: 1.3,
      iridescence: 0.5
    },
    habitat: 'Soft, tea-stained forest streams of Malaysia, Singapore, and Sumatra.',
    facts: [
      'The black patch on its side is shaped like a little pork chop.',
      'Unlike most fish, it sticks its eggs to the underside of a leaf.',
      'Its copper-orange color glows in the dark tea-colored water of its home.'
    ],
    care: 'Easy'
  },
  {
    id: 'chili_rasbora',
    common: 'Chili Rasbora',
    scientific: 'Boraras brigittae',
    water: 'fresh',
    adultSizeCm: 2,
    bioload: 1,
    minSchool: 10,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.8,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.6,
    colors: {
      base: '#d02030',
      belly: '#e06050',
      fin: '#c81828',
      pattern: 'lateralStripe',
      patternColor: '#601018',
      patternScale: 1.0,
      iridescence: 0.4
    },
    habitat: 'Dark peat swamps and blackwater pools of southwestern Borneo.',
    facts: [
      'It is one of the tiniest aquarium fish — smaller than a paperclip.',
      'It is named chili because it is bright red like a chili pepper.',
      'Even though it is tiny, it feels brave and colorful in a big group.'
    ],
    care: 'Medium'
  },
  {
    id: 'ember_tetra',
    common: 'Ember Tetra',
    scientific: 'Hyphessobrycon amandae',
    water: 'fresh',
    adultSizeCm: 2,
    bioload: 1,
    minSchool: 8,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.9,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.6,
    colors: {
      base: '#f07030',
      belly: '#f09858',
      fin: '#e86828',
      pattern: 'none',
      patternColor: '#c05020',
      patternScale: 1.0,
      iridescence: 0.4
    },
    habitat: 'Slow, shallow forest streams of the Araguaia River basin in Brazil.',
    facts: [
      'It glows orange like a tiny floating ember from a campfire.',
      'A school of embers drifting through plants looks like floating sparks.',
      'It was named after the mother of the scientist who discovered it.'
    ],
    care: 'Easy'
  },
  {
    id: 'rummy_nose_tetra',
    common: 'Rummy Nose Tetra',
    scientific: 'Hemigrammus rhodostomus',
    water: 'fresh',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 8,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.1,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 5,
    archetype: 'torpedo',
    size: 0.85,
    colors: {
      base: '#c9ced2',
      belly: '#e8ecee',
      fin: '#d8dcde',
      pattern: 'patches',
      patternColor: '#d81818',
      patternScale: 1.2,
      iridescence: 0.6
    },
    habitat: 'Blackwater rivers of the lower Amazon and Orinoco basins in South America.',
    facts: [
      'Its bright red nose fades to pale when the water is not clean — like a built-in warning light.',
      'Its tail has black and white stripes like a checkered racing flag.',
      'Rummy noses school tighter than almost any other tetra, moving as one.'
    ],
    care: 'Medium'
  },
  {
    id: 'black_neon_tetra',
    common: 'Black Neon Tetra',
    scientific: 'Hyphessobrycon herbertaxelrodi',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.8,
    colors: {
      base: '#3a3a38',
      belly: '#8a8a80',
      fin: '#9a9a90',
      pattern: 'lateralStripe',
      patternColor: '#d8e8c0',
      patternScale: 1.0,
      iridescence: 0.7
    },
    habitat: 'Small acidic streams and flooded areas of the Paraguay River basin in Brazil.',
    facts: [
      'It has two racing stripes: a shiny greenish-white one above a black one.',
      'The top half of its eye is bright orange, like a tiny sunset.',
      'It likes to swim under floating plants that make cozy shade.'
    ],
    care: 'Easy'
  },
  {
    id: 'black_skirt_tetra',
    common: 'Black Skirt Tetra',
    scientific: 'Gymnocorymbus ternetzi',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 2,
    minSchool: 6,
    temperament: 'semi',
    predator: false,
    finNipper: true,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.9,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.95,
    shape: { height: 1.4, finFlow: 1.0 },
    colors: {
      base: '#a8b0b4',
      belly: '#c8ced0',
      fin: '#2a2a2e',
      pattern: 'stripesV',
      patternColor: '#1e1e22',
      patternScale: 0.8,
      iridescence: 0.4
    },
    habitat: 'Slow rivers and creeks of the Paraguay and Guaporé basins in South America.',
    facts: [
      'Its big black bottom fin flows like a fancy twirling skirt.',
      'Young black skirts are darkest — they get lighter as they grow up.',
      'It sometimes nibbles long flowy fins, so slow fancy fish are not good roommates.'
    ],
    care: 'Easy'
  },
  {
    id: 'serpae_tetra',
    common: 'Serpae Tetra',
    scientific: 'Hyphessobrycon eques',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 8,
    temperament: 'semi',
    predator: false,
    finNipper: true,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.8,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#d03828',
      belly: '#e06048',
      fin: '#c82818',
      pattern: 'patches',
      patternColor: '#1a1a1a',
      patternScale: 0.9,
      iridescence: 0.3
    },
    habitat: 'Quiet, plant-choked backwaters of the Amazon and Paraguay basins.',
    facts: [
      'It is fire-engine red with a black comma mark behind its head.',
      'Its dorsal fin looks like a little black flag with a white edge.',
      'Serpaes swim in quick bursts, dart-dart-stop, instead of gliding.'
    ],
    care: 'Easy'
  },
  {
    id: 'congo_tetra',
    common: 'Congo Tetra',
    scientific: 'Phenacogrammus interruptus',
    water: 'fresh',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: true,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 9,
    archetype: 'torpedo',
    size: 1.1,
    shape: { height: 1.2, finFlow: 1.3 },
    colors: {
      base: '#7aa0c0',
      belly: '#c8d0c0',
      fin: '#a8b8c8',
      pattern: 'lateralStripe',
      patternColor: '#d0a040',
      patternScale: 1.3,
      iridescence: 0.9
    },
    habitat: 'Murky rivers and streams of the Congo River basin in central Africa.',
    facts: [
      'Its scales shimmer blue, gold, and violet all at once, like a rainbow.',
      'Grown-up males grow long flowing white-edged fins like ribbons.',
      'It is one of the few famous aquarium tetras that comes from Africa, not South America.'
    ],
    care: 'Medium'
  },
  {
    id: 'glowlight_tetra',
    common: 'Glowlight Tetra',
    scientific: 'Hemigrammus erythrozonus',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.9,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 3,
    archetype: 'torpedo',
    size: 0.75,
    colors: {
      base: '#b8beb8',
      belly: '#d8ddd8',
      fin: '#c8cec8',
      pattern: 'lateralStripe',
      patternColor: '#ff7020',
      patternScale: 1.0,
      iridescence: 0.6
    },
    habitat: 'Dark, tea-colored creeks of the Essequibo River in Guyana, South America.',
    facts: [
      'The orange stripe down its side glows like the filament in a lightbulb.',
      'Its see-through body helps it hide in dark forest water.',
      'When it lays eggs it does a little flip, rolling upside down.'
    ],
    care: 'Easy'
  },
  {
    id: 'cherry_barb',
    common: 'Cherry Barb',
    scientific: 'Puntius titteya',
    water: 'fresh',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.9,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.8,
    colors: {
      base: '#c83030',
      belly: '#e08060',
      fin: '#c02828',
      pattern: 'lateralStripe',
      patternColor: '#6a2020',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Shady, slow rainforest streams of Sri Lanka.',
    facts: [
      'Males turn deep cherry red to show off, especially at breakfast time.',
      'It comes from only one island in the whole world: Sri Lanka.',
      'It is gentle and shy, the opposite of its cousin the tiger barb.'
    ],
    care: 'Easy'
  },
  {
    id: 'pearl_gourami',
    common: 'Pearl Gourami',
    scientific: 'Trichopodus leerii',
    water: 'fresh',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: true,
    tags: [],
    zone: 'top',
    speed: 0.5,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 10,
    archetype: 'gourami',
    size: 1.1,
    shape: { height: 1.0, finFlow: 1.3 },
    colors: {
      base: '#9a8a72',
      belly: '#e0703a',
      fin: '#a89a82',
      pattern: 'spots',
      patternColor: '#f0e8d8',
      patternScale: 1.6,
      iridescence: 0.6
    },
    habitat: 'Acidic peat swamps and lowland wetlands of Thailand, Malaysia, and Indonesia.',
    facts: [
      'Its whole body is dusted with shiny spots like tiny pearls.',
      'Its feeler fins are as long as its body and touch everything gently.',
      'Males get a glowing orange chest, like they are wearing a sunset.'
    ],
    care: 'Easy'
  },
  {
    id: 'honey_gourami',
    common: 'Honey Gourami',
    scientific: 'Trichogaster chuna',
    water: 'fresh',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'top',
    speed: 0.5,
    schooling: 'pair',
    diet: ['flake', 'frozen'],
    price: 8,
    archetype: 'gourami',
    size: 0.7,
    colors: {
      base: '#e8a030',
      belly: '#f0c060',
      fin: '#e89828',
      pattern: 'none',
      patternColor: '#c07820',
      patternScale: 1.0,
      iridescence: 0.4
    },
    habitat: 'Thickly planted ponds and flooded fields of India and Bangladesh.',
    facts: [
      'It is the color of golden honey and just as sweet-tempered.',
      'It can spit little jets of water to knock bugs off plants above the surface.',
      'Like all gouramis, it takes sips of air from above the water.'
    ],
    care: 'Easy'
  },
  {
    id: 'bolivian_ram',
    common: 'Bolivian Ram',
    scientific: 'Mikrogeophagus altispinosus',
    water: 'fresh',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.6,
    schooling: 'pair',
    diet: ['pellet', 'frozen'],
    price: 10,
    archetype: 'cichlid',
    size: 0.9,
    colors: {
      base: '#c8b088',
      belly: '#d8c8a0',
      fin: '#e07040',
      pattern: 'eyespot',
      patternColor: '#2a2a2a',
      patternScale: 1.0,
      iridescence: 0.4
    },
    habitat: 'Calm, sandy river edges of the Bolivian and Brazilian Amazon.',
    facts: [
      'It swims forward in little hops: glide, stop, glide, stop.',
      'Its tail fin has bright red-orange edges like flame trim.',
      'It is tougher and easier to keep than its fancy cousin the blue ram.'
    ],
    care: 'Easy'
  },
  {
    id: 'apistogramma_cacatuoides',
    common: 'Cockatoo Dwarf Cichlid',
    scientific: 'Apistogramma cacatuoides',
    water: 'fresh',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.6,
    schooling: 'pair',
    diet: ['pellet', 'frozen'],
    price: 14,
    archetype: 'cichlid',
    size: 0.85,
    shape: { height: 0.9, finFlow: 1.2 },
    colors: {
      base: '#a8a088',
      belly: '#c8c0a8',
      fin: '#e05020',
      pattern: 'lateralStripe',
      patternColor: '#2a2a2a',
      patternScale: 1.0,
      iridescence: 0.4
    },
    habitat: 'Shallow leaf-littered creeks of the Peruvian Amazon rainforest.',
    facts: [
      'The male\'s spiky dorsal fin sticks up like a cockatoo\'s crest.',
      'Its orange tail is splashed with black spots like flame and soot.',
      'Moms turn bright yellow when guarding babies and lead them around like ducklings.'
    ],
    care: 'Medium'
  },
  {
    id: 'kribensis',
    common: 'Kribensis',
    scientific: 'Pelvicachromis pulcher',
    water: 'fresh',
    adultSizeCm: 10,
    bioload: 2,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.6,
    schooling: 'pair',
    diet: ['pellet', 'frozen'],
    price: 9,
    archetype: 'cichlid',
    size: 0.95,
    colors: {
      base: '#9a8a80',
      belly: '#d05070',
      fin: '#b0a090',
      pattern: 'lateralStripe',
      patternColor: '#3a2a2a',
      patternScale: 1.0,
      iridescence: 0.4
    },
    habitat: 'Shaded forest streams and river deltas of Nigeria and Cameroon in West Africa.',
    facts: [
      'Moms show off a berry-pink tummy that glows brightest at baby time.',
      'Krib parents raise their babies in caves and take them on walks around the tank.',
      'Both mom and dad guard the babies together, wiggling to call them home.'
    ],
    care: 'Easy'
  },
  {
    id: 'electric_yellow_lab',
    common: 'Electric Yellow Lab',
    scientific: 'Labidochromis caeruleus',
    water: 'fresh',
    adultSizeCm: 10,
    bioload: 4,
    minSchool: 5,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.9,
    schooling: 'loose',
    diet: ['pellet', 'flake'],
    price: 9,
    archetype: 'cichlid',
    size: 1.0,
    colors: {
      base: '#f0c020',
      belly: '#f0cc40',
      fin: '#e8b818',
      pattern: 'lateralStripe',
      patternColor: '#1a1a1a',
      patternScale: 0.7,
      iridescence: 0.3
    },
    habitat: 'Rocky underwater cliffs of Lake Malawi in East Africa.',
    facts: [
      'It is banana yellow with a bold black stripe on its top fin.',
      'Moms carry their eggs and babies inside their mouths to keep them safe.',
      'It comes from Lake Malawi, a lake so big it looks like an ocean.'
    ],
    care: 'Medium'
  },
  {
    id: 'black_molly',
    common: 'Black Molly',
    scientific: 'Poecilia sphenops',
    water: 'fresh',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'all',
    speed: 0.8,
    schooling: 'loose',
    diet: ['flake', 'algae'],
    price: 5,
    archetype: 'livebearer',
    size: 1.1,
    colors: {
      base: '#1a1a1a',
      belly: '#242424',
      fin: '#1e1e1e',
      pattern: 'none',
      patternColor: '#000000',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Warm rivers, coastal streams, and even brackish lagoons from Mexico to Colombia.',
    facts: [
      'It is velvet black from nose to tail, like a shadow that swims.',
      'Molly babies are born live and can swim and hide right away.',
      'It nibbles soft algae off plants and rocks like a little lawnmower.'
    ],
    care: 'Easy'
  },
  {
    id: 'platy',
    common: 'Platy',
    scientific: 'Xiphophorus maculatus',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 2,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'all',
    speed: 0.8,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'livebearer',
    size: 0.9,
    colors: {
      base: '#e86020',
      belly: '#f08840',
      fin: '#e05818',
      pattern: 'none',
      patternColor: '#c04010',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Warm, weedy canals and spring-fed streams of Mexico and Central America.',
    facts: [
      'Platies come in almost every color, like a box of crayons.',
      'A mother platy can have dozens of live babies at once.',
      'It is one of the friendliest, easiest fish a beginner can keep.'
    ],
    care: 'Easy'
  },
  {
    id: 'swordtail',
    common: 'Swordtail',
    scientific: 'Xiphophorus hellerii',
    water: 'fresh',
    adultSizeCm: 12,
    bioload: 2,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'all',
    speed: 1.0,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 5,
    archetype: 'livebearer',
    size: 1.2,
    colors: {
      base: '#d84020',
      belly: '#e87040',
      fin: '#d03818',
      pattern: 'gradientTail',
      patternColor: '#1a1a1a',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Fast, rocky streams and springs of Mexico and Guatemala.',
    facts: [
      'Males grow a long sword-shaped tail point — but it is soft, not sharp.',
      'The sword is just for showing off to other swordtails.',
      'Swordtails are great jumpers, so their tank needs a lid.'
    ],
    care: 'Easy'
  },
  {
    id: 'endlers_livebearer',
    common: "Endler's Livebearer",
    scientific: 'Poecilia wingei',
    water: 'fresh',
    adultSizeCm: 3,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'top',
    speed: 1.0,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 5,
    archetype: 'livebearer',
    size: 0.6,
    colors: {
      base: '#30a848',
      belly: '#c8c8a0',
      fin: '#e8a020',
      pattern: 'patches',
      patternColor: '#e84018',
      patternScale: 1.2,
      iridescence: 0.9
    },
    habitat: 'Warm, green lagoons on the Caribbean coast of Venezuela.',
    facts: [
      'Males look like tiny neon paint splatters of green, orange, and black.',
      'It is a wild cousin of the guppy, found in just a few lagoons on Earth.',
      'It zips around near the surface all day hunting for tiny food bits.'
    ],
    care: 'Easy'
  },
  {
    id: 'otocinclus',
    common: 'Otocinclus',
    scientific: 'Otocinclus vittatus',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.5,
    schooling: 'loose',
    diet: ['algae'],
    price: 5,
    archetype: 'cory',
    size: 0.65,
    shape: { height: 0.7, finFlow: 1.0 },
    colors: {
      base: '#b8b8a0',
      belly: '#e0e0d0',
      fin: '#c8c8b8',
      pattern: 'lateralStripe',
      patternColor: '#3a3a30',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Plant-filled edges of slow rivers across much of South America.',
    facts: [
      'It spends all day stuck to leaves and glass, vacuuming up algae.',
      'Its lips make a suction cup so strong it can rest in flowing water.',
      'It is so gentle it can live safely with baby shrimp.'
    ],
    care: 'Medium'
  },
  {
    id: 'clown_pleco',
    common: 'Clown Pleco',
    scientific: 'Panaqolus maccus',
    water: 'fresh',
    adultSizeCm: 9,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['algae', 'pellet'],
    price: 12,
    archetype: 'pleco',
    size: 0.8,
    colors: {
      base: '#3a3028',
      belly: '#5a4c3a',
      fin: '#3a3028',
      pattern: 'stripesV',
      patternColor: '#d8a858',
      patternScale: 1.1,
      iridescence: 0.1
    },
    habitat: 'Sunken wood piles in rivers of Venezuela and Colombia.',
    facts: [
      'It actually eats wood — it rasps on sunken branches for dinner.',
      'Its tan and brown stripes look like swirls on a piece of candy.',
      'It hides all day and sneaks out at night to munch.'
    ],
    care: 'Easy'
  },
  {
    id: 'yoyo_loach',
    common: 'Yoyo Loach',
    scientific: 'Botia almorhae',
    water: 'fresh',
    adultSizeCm: 13,
    bioload: 4,
    minSchool: 5,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.9,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 8,
    archetype: 'loach',
    size: 1.0,
    colors: {
      base: '#c8c8d0',
      belly: '#e0e0e4',
      fin: '#b8b8c0',
      pattern: 'patches',
      patternColor: '#2a2a3a',
      patternScale: 1.2,
      iridescence: 0.3
    },
    habitat: 'Rocky pools and slow stretches of rivers in India and Pakistan.',
    facts: [
      'The squiggles on its side seem to spell Y-O-Y-O, which gave it its name.',
      'It makes little clicking sounds when it is excited about food.',
      'It loves to eat snails, tugging them right out of their shells.'
    ],
    care: 'Medium'
  },
  {
    id: 'clown_loach',
    common: 'Clown Loach',
    scientific: 'Chromobotia macracanthus',
    water: 'fresh',
    adultSizeCm: 26,
    bioload: 8,
    minSchool: 5,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.9,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 15,
    archetype: 'loach',
    size: 1.4,
    colors: {
      base: '#e8901f',
      belly: '#f0b050',
      fin: '#d82818',
      pattern: 'stripesV',
      patternColor: '#1a1a1a',
      patternScale: 0.7,
      iridescence: 0.2
    },
    habitat: 'Big rainforest rivers of Sumatra and Borneo in Indonesia.',
    facts: [
      'It sometimes naps lying on its side, which looks worrying but is normal.',
      'It has a secret switchblade spine under each eye for protecting itself.',
      'Clown loaches click loudly when they are happy or squabbling over food.'
    ],
    care: 'Medium'
  },
  {
    id: 'dojo_loach',
    common: 'Dojo Loach',
    scientific: 'Misgurnus anguillicaudatus',
    water: 'fresh',
    adultSizeCm: 25,
    bioload: 4,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['coldwater'],
    zone: 'bottom',
    speed: 0.6,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 10,
    archetype: 'eel',
    size: 1.4,
    colors: {
      base: '#b0a070',
      belly: '#d8cca8',
      fin: '#a09068',
      pattern: 'spots',
      patternColor: '#6a5c3a',
      patternScale: 1.3,
      iridescence: 0.1
    },
    habitat: 'Cool muddy ponds, rice paddies, and slow rivers of East Asia.',
    facts: [
      'People call it the weather loach because it wiggles wildly before storms.',
      'It can feel changes in air pressure that people cannot notice.',
      'It likes to burrow in soft sand until only its whiskery face shows.'
    ],
    care: 'Easy'
  },
  {
    id: 'siamese_algae_eater',
    common: 'Siamese Algae Eater',
    scientific: 'Crossocheilus oblongus',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'bottom',
    speed: 1.1,
    schooling: 'loose',
    diet: ['algae', 'pellet'],
    price: 6,
    archetype: 'torpedo',
    size: 1.1,
    colors: {
      base: '#b8ab90',
      belly: '#e0d8c0',
      fin: '#c8c0a8',
      pattern: 'lateralStripe',
      patternColor: '#1a1a1a',
      patternScale: 1.1,
      iridescence: 0.2
    },
    habitat: 'Flowing streams and flooded forests of Thailand and the Malay Peninsula.',
    facts: [
      'It is one of the only fish that eats stubborn black brush algae.',
      'Its black racing stripe runs from its nose all the way into its tail.',
      'It cannot float in place, so it rests propped up on its fins.'
    ],
    care: 'Easy'
  },
  {
    id: 'white_cloud_minnow',
    common: 'White Cloud Mountain Minnow',
    scientific: 'Tanichthys albonubes',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['coldwater'],
    zone: 'mid',
    speed: 1.1,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 3,
    archetype: 'torpedo',
    size: 0.7,
    colors: {
      base: '#7a8a6a',
      belly: '#c8c8b0',
      fin: '#d03030',
      pattern: 'lateralStripe',
      patternColor: '#f0e8b0',
      patternScale: 1.0,
      iridescence: 0.7
    },
    habitat: 'Cool, clear mountain streams near White Cloud Mountain in southern China.',
    facts: [
      'It is happy in cool water and does not need a tank heater.',
      'Its shiny gold stripe and red tail earned it the nickname "poor man\'s neon".',
      'It was first discovered by a boy scout leader on a Chinese mountain.'
    ],
    care: 'Easy'
  },
  {
    id: 'celestial_pearl_danio',
    common: 'Celestial Pearl Danio',
    scientific: 'Danio margaritatus',
    water: 'fresh',
    adultSizeCm: 2,
    bioload: 1,
    minSchool: 8,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.8,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 6,
    archetype: 'torpedo',
    size: 0.6,
    colors: {
      base: '#2a3a5a',
      belly: '#c86028',
      fin: '#e06020',
      pattern: 'spots',
      patternColor: '#f0e8c0',
      patternScale: 1.3,
      iridescence: 0.6
    },
    habitat: 'Tiny, shallow plant-filled ponds in the mountains of Myanmar.',
    facts: [
      'Its dark blue body is speckled with pearly dots like a starry night sky.',
      'The whole species was only discovered in 2006, in little mountain ponds.',
      'Its fins are striped orange and black like tiny tiger tails.'
    ],
    care: 'Medium'
  },
  {
    id: 'boesemani_rainbowfish',
    common: 'Boesemani Rainbowfish',
    scientific: 'Melanotaenia boesemani',
    water: 'fresh',
    adultSizeCm: 11,
    bioload: 4,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.2,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 14,
    archetype: 'torpedo',
    size: 1.2,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#5a7a9a',
      belly: '#8a9aa8',
      fin: '#e88020',
      pattern: 'gradientTail',
      patternColor: '#e88020',
      patternScale: 1.4,
      iridescence: 0.9
    },
    habitat: 'Three clear lakes in the Ayamaru region of West Papua, Indonesia.',
    facts: [
      'Its front half is blue-purple and its back half is glowing orange, like two fish in one.',
      'In the morning light its colors get extra bright to impress friends.',
      'It comes from just three little lakes in the whole world.'
    ],
    care: 'Easy'
  },
  {
    id: 'praecox_rainbowfish',
    common: 'Dwarf Neon Rainbowfish',
    scientific: 'Melanotaenia praecox',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.2,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 8,
    archetype: 'torpedo',
    size: 0.85,
    shape: { height: 1.2, finFlow: 1.0 },
    colors: {
      base: '#8ab8d8',
      belly: '#b8d0e0',
      fin: '#d04030',
      pattern: 'none',
      patternColor: '#6a98b8',
      patternScale: 1.0,
      iridescence: 0.9
    },
    habitat: 'Fast, clear jungle rivers of the Mamberamo basin in New Guinea.',
    facts: [
      'Its whole body flashes electric blue like a swimming jewel.',
      'Its fins are bright red, making it look dressed for a party.',
      'Rainbowfish shimmer because their scales bend light like tiny prisms.'
    ],
    care: 'Easy'
  },
  {
    id: 'bala_shark',
    common: 'Bala Shark',
    scientific: 'Balantiocheilos melanopterus',
    water: 'fresh',
    adultSizeCm: 30,
    bioload: 8,
    minSchool: 4,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'mid',
    speed: 1.4,
    schooling: 'loose',
    diet: ['flake', 'pellet', 'frozen'],
    price: 12,
    archetype: 'shark',
    size: 1.5,
    colors: {
      base: '#c0c8d0',
      belly: '#e8ecf0',
      fin: '#d8c860',
      pattern: 'gradientTail',
      patternColor: '#1a1a1a',
      patternScale: 1.0,
      iridescence: 0.7
    },
    habitat: 'Large rivers and lakes of Southeast Asia, including Borneo and Sumatra.',
    facts: [
      'It looks like a tiny silver shark but only eats flakes and bugs, never fish friends.',
      'Its fins are trimmed in black like they were dipped in ink.',
      'It is a champion jumper, so its tank always needs a tight lid.'
    ],
    care: 'Medium'
  },
  {
    id: 'rainbow_shark',
    common: 'Rainbow Shark',
    scientific: 'Epalzeorhynchos frenatum',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'bottom',
    speed: 1.1,
    schooling: 'solo',
    diet: ['pellet', 'algae', 'frozen'],
    price: 8,
    archetype: 'shark',
    size: 1.0,
    colors: {
      base: '#2a2a30',
      belly: '#3a3a40',
      fin: '#d82020',
      pattern: 'none',
      patternColor: '#1a1a1a',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Sandy river bottoms and flooded plains of Thailand and Laos.',
    facts: [
      'Its charcoal body and bright red fins make it look like a race car.',
      'It picks one cave or plant as its home and guards it proudly.',
      'Two rainbow sharks will argue, so each tank gets just one.'
    ],
    care: 'Medium'
  },
  {
    id: 'redtail_shark',
    common: 'Red-Tail Shark',
    scientific: 'Epalzeorhynchos bicolor',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'bottom',
    speed: 1.1,
    schooling: 'solo',
    diet: ['pellet', 'algae', 'frozen'],
    price: 9,
    archetype: 'shark',
    size: 1.0,
    colors: {
      base: '#141414',
      belly: '#1e1e1e',
      fin: '#141414',
      pattern: 'gradientTail',
      patternColor: '#e01818',
      patternScale: 1.4,
      iridescence: 0.2
    },
    habitat: 'The Chao Phraya River basin in Thailand, where it is now extremely rare in the wild.',
    facts: [
      'Its body is jet black and only its tail is bright red, like a flag.',
      'It is almost gone from the wild, but millions live safely in aquariums.',
      'It patrols the bottom of the tank like a little security guard.'
    ],
    care: 'Medium'
  },
  {
    id: 'denison_barb',
    common: 'Denison Barb',
    scientific: 'Sahyadria denisonii',
    water: 'fresh',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.5,
    schooling: 'tight',
    diet: ['flake', 'pellet', 'frozen'],
    price: 20,
    archetype: 'torpedo',
    size: 1.2,
    colors: {
      base: '#c8ccc8',
      belly: '#e8ece8',
      fin: '#d8dcd8',
      pattern: 'lateralStripe',
      patternColor: '#d81818',
      patternScale: 1.0,
      iridescence: 0.6
    },
    habitat: 'Fast, rocky, oxygen-rich rivers of the Western Ghats mountains in India.',
    facts: [
      'A bright red stripe streaks along its side like a torpedo flame.',
      'It loves fast water and swims against the current for fun.',
      'It is also called the Miss Kerala fish after its home in India.'
    ],
    care: 'Medium'
  },
  {
    id: 'pictus_catfish',
    common: 'Pictus Catfish',
    scientific: 'Pimelodus pictus',
    water: 'fresh',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 4,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 1.3,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 10,
    archetype: 'cory',
    size: 1.3,
    shape: { height: 0.8, finFlow: 1.1 },
    colors: {
      base: '#c8ced4',
      belly: '#e8ecee',
      fin: '#b8bec4',
      pattern: 'spots',
      patternColor: '#1e1e22',
      patternScale: 1.2,
      iridescence: 0.5
    },
    habitat: 'Sandy stretches of the Amazon and Orinoco rivers in South America.',
    facts: [
      'Its whiskers are longer than its whole body and sweep around like radar.',
      'It never stops cruising, gliding along the bottom day and night.',
      'It will slurp up any fish tiny enough to fit in its mouth, so friends must be bigger.'
    ],
    care: 'Medium'
  },
  {
    id: 'glass_catfish',
    common: 'Glass Catfish',
    scientific: 'Kryptopterus vitreolus',
    water: 'fresh',
    adultSizeCm: 7,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.7,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 8,
    archetype: 'eel',
    size: 0.9,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#cfe0e0',
      belly: '#e0eeee',
      fin: '#d8e8e8',
      pattern: 'none',
      patternColor: '#b0c8c8',
      patternScale: 1.0,
      iridescence: 0.7
    },
    habitat: 'Slow, shaded rivers of peninsular Thailand.',
    facts: [
      'Its body is see-through — you can see its tiny bones and heartbeat.',
      'When light hits it just right, it shimmers with rainbow colors.',
      'The see-through trick makes it almost invisible to hungry predators.'
    ],
    care: 'Medium'
  },
  {
    id: 'marble_hatchetfish',
    common: 'Marble Hatchetfish',
    scientific: 'Carnegiella strigata',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'top',
    speed: 0.7,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 6,
    archetype: 'torpedo',
    size: 0.7,
    shape: { height: 1.5, finFlow: 1.0 },
    colors: {
      base: '#c0b494',
      belly: '#e8e0c8',
      fin: '#c8c0a8',
      pattern: 'patches',
      patternColor: '#4a3a28',
      patternScale: 1.2,
      iridescence: 0.4
    },
    habitat: 'The calm, leafy surface of Amazon rainforest creeks in South America.',
    facts: [
      'It can leap out of the water and glide to escape danger.',
      'Its deep chest is packed with muscles that power its great jumps.',
      'It spends its whole life right at the surface, watching for falling bugs.'
    ],
    care: 'Medium'
  },
  {
    id: 'pea_puffer',
    common: 'Pea Puffer',
    scientific: 'Carinotetraodon travancoricus',
    water: 'fresh',
    adultSizeCm: 3,
    bioload: 1,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: true,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.5,
    schooling: 'loose',
    diet: ['frozen'],
    price: 8,
    archetype: 'puffer',
    size: 0.6,
    colors: {
      base: '#c8c832',
      belly: '#e8e888',
      fin: '#d8d858',
      pattern: 'spots',
      patternColor: '#2a4a1a',
      patternScale: 1.2,
      iridescence: 0.3
    },
    habitat: 'Slow, weedy rivers and lakes of Kerala in southern India.',
    facts: [
      'It is the smallest pufferfish in the world, about the size of a pea.',
      'Its eyes can swivel in two different directions at the same time.',
      'It hunts little snails and crunches them up like popcorn.'
    ],
    care: 'Medium'
  },
  {
    id: 'severum',
    common: 'Gold Severum',
    scientific: 'Heros severus',
    water: 'fresh',
    adultSizeCm: 20,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.6,
    schooling: 'pair',
    diet: ['pellet', 'frozen', 'algae'],
    price: 18,
    archetype: 'cichlid',
    size: 1.5,
    shape: { height: 1.2, finFlow: 1.1 },
    colors: {
      base: '#e8c858',
      belly: '#f0d878',
      fin: '#e0be48',
      pattern: 'none',
      patternColor: '#c8a838',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Calm, deep river bends of the Amazon and Orinoco basins.',
    facts: [
      'People call it the poor man\'s discus because of its round shape.',
      'It can learn to recognize its owner and beg at the glass for food.',
      'Wild severums snack on fruits and seeds that drop into the river.'
    ],
    care: 'Medium'
  },
  {
    id: 'electric_blue_acara',
    common: 'Electric Blue Acara',
    scientific: 'Andinoacara pulcher',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.7,
    schooling: 'pair',
    diet: ['pellet', 'frozen'],
    price: 15,
    archetype: 'cichlid',
    size: 1.2,
    colors: {
      base: '#4a9ae0',
      belly: '#6ab0e8',
      fin: '#58a4e4',
      pattern: 'none',
      patternColor: '#e8a030',
      patternScale: 1.0,
      iridescence: 0.9
    },
    habitat: 'Bred from blue acaras of the rivers of Venezuela and Trinidad.',
    facts: [
      'It glows electric blue from head to tail like a neon sign.',
      'For a cichlid it is a real softie, calm enough for community tanks.',
      'Acara parents dig a nest pit and both guard the babies.'
    ],
    care: 'Easy'
  },
  {
    id: 'keyhole_cichlid',
    common: 'Keyhole Cichlid',
    scientific: 'Cleithracara maronii',
    water: 'fresh',
    adultSizeCm: 10,
    bioload: 4,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.5,
    schooling: 'pair',
    diet: ['pellet', 'frozen'],
    price: 10,
    archetype: 'cichlid',
    size: 1.0,
    colors: {
      base: '#c0ac84',
      belly: '#d8c8a8',
      fin: '#b8a47c',
      pattern: 'eyespot',
      patternColor: '#2a2a2a',
      patternScale: 1.1,
      iridescence: 0.2
    },
    habitat: 'Quiet, tannin-stained creeks of Guyana and Suriname in South America.',
    facts: [
      'The dark keyhole-shaped mark on its side gives it its name.',
      'It is one of the shyest, gentlest cichlids in the whole hobby.',
      'When it feels nervous it fades pale and hides near driftwood.'
    ],
    care: 'Easy'
  },
  {
    id: 'firemouth_cichlid',
    common: 'Firemouth Cichlid',
    scientific: 'Thorichthys meeki',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.6,
    schooling: 'pair',
    diet: ['pellet', 'frozen'],
    price: 10,
    archetype: 'cichlid',
    size: 1.2,
    colors: {
      base: '#8a98a0',
      belly: '#e03020',
      fin: '#98a4ac',
      pattern: 'stripesV',
      patternColor: '#3a4048',
      patternScale: 0.8,
      iridescence: 0.4
    },
    habitat: 'Slow rivers and limestone sinkhole pools of Mexico and Central America.',
    facts: [
      'Its throat and chest blaze fiery red, like it swallowed a flame.',
      'To look big and scary it puffs out its bright red throat pouch.',
      'It is mostly bluff — it would rather show off than really fight.'
    ],
    care: 'Medium'
  },
  {
    id: 'rosy_barb',
    common: 'Rosy Barb',
    scientific: 'Pethia conchonius',
    water: 'fresh',
    adultSizeCm: 10,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['coldwater'],
    zone: 'mid',
    speed: 1.2,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 1.0,
    colors: {
      base: '#d86050',
      belly: '#e89078',
      fin: '#d05040',
      pattern: 'eyespot',
      patternColor: '#2a2a2a',
      patternScale: 0.8,
      iridescence: 0.6
    },
    habitat: 'Cool lakes and fast streams of northern India and Bangladesh.',
    facts: [
      'Males blush a rosy pink-red, brightest when showing off.',
      'It is tough enough to live in cool water without a heater.',
      'It has a single black dot near its tail like a period at the end of a sentence.'
    ],
    care: 'Easy'
  },
  {
    id: 'emperor_tetra',
    common: 'Emperor Tetra',
    scientific: 'Nematobrycon palmeri',
    water: 'fresh',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.8,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 5,
    archetype: 'torpedo',
    size: 0.85,
    colors: {
      base: '#8a86a0',
      belly: '#c8c4d0',
      fin: '#a8a4b8',
      pattern: 'lateralStripe',
      patternColor: '#1a1a24',
      patternScale: 1.2,
      iridescence: 0.6
    },
    habitat: 'Small, shady rainforest streams of the San Juan River basin in Colombia.',
    facts: [
      'Males have a three-pointed tail like a tiny trident.',
      'Its eyes shine blue-green like little gemstones.',
      'A wide black-and-purple band runs down its side like a royal sash.'
    ],
    care: 'Easy'
  },
  {
    id: 'diamond_tetra',
    common: 'Diamond Tetra',
    scientific: 'Moenkhausia pittieri',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.9,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 6,
    archetype: 'torpedo',
    size: 0.95,
    shape: { height: 1.2, finFlow: 1.2 },
    colors: {
      base: '#b0a8c0',
      belly: '#d8d4e0',
      fin: '#c0b8d0',
      pattern: 'none',
      patternColor: '#9088a8',
      patternScale: 1.0,
      iridescence: 0.9
    },
    habitat: 'Warm, weedy Lake Valencia and nearby streams in Venezuela.',
    facts: [
      'Every scale sparkles gold, violet, and green, like crushed diamonds.',
      'Young diamond tetras look plain — they grow their sparkle as they age.',
      'The top half of its eye glows orange-red like a tiny sunrise.'
    ],
    care: 'Easy'
  },
  {
    id: 'gold_barb',
    common: 'Gold Barb',
    scientific: 'Barbodes semifasciolatus',
    water: 'fresh',
    adultSizeCm: 7,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['coldwater'],
    zone: 'mid',
    speed: 1.0,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.95,
    colors: {
      base: '#e8c030',
      belly: '#f0d868',
      fin: '#e05828',
      pattern: 'patches',
      patternColor: '#2a2a2a',
      patternScale: 0.9,
      iridescence: 0.4
    },
    habitat: 'Slow streams and ponds of southern China and Vietnam.',
    facts: [
      'It is golden yellow with little black dashes along its back.',
      'Wild gold barbs are actually green — the gold kind was bred by people.',
      'It happily lives in cool water, so it suits unheated tanks.'
    ],
    care: 'Easy'
  },
  {
    id: 'lemon_tetra',
    common: 'Lemon Tetra',
    scientific: 'Hyphessobrycon pulchripinnis',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.9,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.8,
    colors: {
      base: '#d8d888',
      belly: '#e8e8b0',
      fin: '#e8e030',
      pattern: 'none',
      patternColor: '#c8c020',
      patternScale: 1.0,
      iridescence: 0.5
    },
    habitat: 'Clear, shallow streams of the Tapajós River basin in Brazil.',
    facts: [
      'It is soft lemon yellow with glowing yellow fin edges.',
      'The top of its eye is painted bright red like a tiny ruby.',
      'Its colors turn richer and deeper when it feels safe in a big school.'
    ],
    care: 'Easy'
  },
  {
    id: 'penguin_tetra',
    common: 'Penguin Tetra',
    scientific: 'Thayeria boehlkei',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.9,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.85,
    colors: {
      base: '#c8c8b8',
      belly: '#e8e8dc',
      fin: '#d8d8cc',
      pattern: 'lateralStripe',
      patternColor: '#1a1a1a',
      patternScale: 1.1,
      iridescence: 0.5
    },
    habitat: 'The Amazon and Araguaia river systems of Brazil and Peru.',
    facts: [
      'It swims tilted with its head up, standing at attention like a penguin.',
      'Its black stripe bends down into the bottom half of its tail like a hockey stick.',
      'The whole school rests at the same funny tilted angle together.'
    ],
    care: 'Easy'
  },
  {
    id: 'silver_hatchetfish',
    common: 'Silver Hatchetfish',
    scientific: 'Gasteropelecus sternicla',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'top',
    speed: 0.7,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 6,
    archetype: 'torpedo',
    size: 0.85,
    shape: { height: 1.5, finFlow: 1.0 },
    colors: {
      base: '#c8ccd0',
      belly: '#e8ecf0',
      fin: '#d8dce0',
      pattern: 'lateralStripe',
      patternColor: '#2a2a2a',
      patternScale: 1.0,
      iridescence: 0.7
    },
    habitat: 'Calm surface waters of rivers in the Guianas and the Amazon basin.',
    facts: [
      'Its chest is shaped like a hatchet blade, which gave it its name.',
      'It can burst from the water and buzz its fins to travel over the surface.',
      'Its upturned mouth is made for grabbing bugs right at the surface film.'
    ],
    care: 'Medium'
  },
  {
    id: 'upside_down_catfish',
    common: 'Upside-Down Catfish',
    scientific: 'Synodontis nigriventris',
    water: 'fresh',
    adultSizeCm: 9,
    bioload: 2,
    minSchool: 4,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'all',
    speed: 0.6,
    schooling: 'loose',
    diet: ['pellet', 'frozen', 'algae'],
    price: 9,
    archetype: 'cory',
    size: 1.0,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#a89078',
      belly: '#5a4a3a',
      fin: '#988068',
      pattern: 'patches',
      patternColor: '#4a3a2a',
      patternScale: 1.2,
      iridescence: 0.1
    },
    habitat: 'Shaded riverbanks of the Congo River basin in central Africa.',
    facts: [
      'It really does swim upside down, belly to the sky, all day long.',
      'Its belly is darker than its back — the opposite of most fish — to hide while flipped.',
      'Swimming upside down lets it grab food stuck under floating leaves.'
    ],
    care: 'Easy'
  },
  {
    id: 'scissortail_rasbora',
    common: 'Scissortail Rasbora',
    scientific: 'Rasbora trilineata',
    water: 'fresh',
    adultSizeCm: 9,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'mid',
    speed: 1.3,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 1.0,
    colors: {
      base: '#c8ccc4',
      belly: '#e4e8e0',
      fin: '#d4d8d0',
      pattern: 'gradientTail',
      patternColor: '#1e1e1e',
      patternScale: 1.0,
      iridescence: 0.6
    },
    habitat: 'Rivers, streams, and flooded fields of the Mekong region in Southeast Asia.',
    facts: [
      'Its forked tail has black-and-white tips that snip open and shut like scissors.',
      'When it stops swimming, the tail keeps twitching in a scissor dance.',
      'It is a shiny silver speedster that loves open swimming room.'
    ],
    care: 'Easy'
  },
  {
    id: 'checker_barb',
    common: 'Checker Barb',
    scientific: 'Oliotius oligolepis',
    water: 'fresh',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 4,
    archetype: 'torpedo',
    size: 0.75,
    colors: {
      base: '#c0a888',
      belly: '#e0d0b8',
      fin: '#d05030',
      pattern: 'spots',
      patternColor: '#2a2a2a',
      patternScale: 1.1,
      iridescence: 0.5
    },
    habitat: 'Clear streams and lake edges of Sumatra, Indonesia.',
    facts: [
      'Its scales make a dark checkerboard pattern along its sides.',
      'Males have red fins edged in black, like painted fingernails.',
      'It is one of the calmest barbs, gentle enough for any community.'
    ],
    care: 'Easy'
  },
  {
    id: 'hillstream_loach',
    common: 'Hillstream Loach',
    scientific: 'Sewellia lineolata',
    water: 'fresh',
    adultSizeCm: 6,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.4,
    schooling: 'loose',
    diet: ['algae', 'pellet'],
    price: 14,
    archetype: 'pleco',
    size: 0.7,
    shape: { height: 0.6, finFlow: 1.0 },
    colors: {
      base: '#8a7a4a',
      belly: '#c8b888',
      fin: '#8a7a4a',
      pattern: 'spots',
      patternColor: '#2a2418',
      patternScale: 1.5,
      iridescence: 0.2
    },
    habitat: 'Rushing, rocky mountain streams of central Vietnam.',
    facts: [
      'It is flat like a pancake and sticks to rocks in rushing water.',
      'Its fins wrap around it to make one big suction cup.',
      'It can scoot up wet glass like a tiny climbing gecko.'
    ],
    care: 'Medium'
  },
  {
    id: 'zebra_loach',
    common: 'Zebra Loach',
    scientific: 'Botia striata',
    water: 'fresh',
    adultSizeCm: 9,
    bioload: 2,
    minSchool: 5,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.8,
    schooling: 'loose',
    diet: ['pellet', 'frozen'],
    price: 9,
    archetype: 'loach',
    size: 0.85,
    colors: {
      base: '#d8c890',
      belly: '#e8dcb0',
      fin: '#c8b880',
      pattern: 'stripesV',
      patternColor: '#4a3a28',
      patternScale: 1.6,
      iridescence: 0.2
    },
    habitat: 'Clear mountain streams of the Western Ghats in India.',
    facts: [
      'It is covered in thin zebra stripes from nose to tail.',
      'It pokes its whiskery snout into every crack looking for snails.',
      'Zebra loaches like to squeeze into one cave together in a pile.'
    ],
    care: 'Medium'
  },
  {
    id: 'sparkling_gourami',
    common: 'Sparkling Gourami',
    scientific: 'Trichopsis pumila',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 4,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'top',
    speed: 0.4,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 6,
    archetype: 'gourami',
    size: 0.6,
    colors: {
      base: '#9a8a72',
      belly: '#c0b098',
      fin: '#c05040',
      pattern: 'spots',
      patternColor: '#58c8d8',
      patternScale: 1.3,
      iridescence: 0.8
    },
    habitat: 'Still, weed-choked ditches and rice paddies of Thailand and Cambodia.',
    facts: [
      'It can actually croak — it makes little clicking-purring sounds you can hear.',
      'Its body twinkles with blue-green sparkles like glitter.',
      'It is small enough to explore between plant leaves like a hummingbird.'
    ],
    care: 'Medium'
  },
  {
    id: 'bloodfin_tetra',
    common: 'Bloodfin Tetra',
    scientific: 'Aphyocharax anisitsi',
    water: 'fresh',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['coldwater'],
    zone: 'mid',
    speed: 1.2,
    schooling: 'tight',
    diet: ['flake', 'frozen'],
    price: 3,
    archetype: 'torpedo',
    size: 0.8,
    colors: {
      base: '#c0c8c0',
      belly: '#e0e8e0',
      fin: '#d81818',
      pattern: 'none',
      patternColor: '#c8d0c8',
      patternScale: 1.0,
      iridescence: 0.7
    },
    habitat: 'Rivers of the Paraná basin in Argentina, Paraguay, and Brazil.',
    facts: [
      'Its silver body ends in fins dipped in bright blood red.',
      'It can live for ten years, a very long time for a small tetra.',
      'It handles cool water better than most tetras, thanks to its southern home.'
    ],
    care: 'Easy'
  },
  {
    id: 'festivum',
    common: 'Festivum (Flag Cichlid)',
    scientific: 'Mesonauta festivus',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 1,
    temperament: 'peaceful',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.6,
    schooling: 'pair',
    diet: ['pellet', 'flake', 'frozen'],
    price: 12,
    archetype: 'cichlid',
    size: 1.2,
    shape: { height: 1.2, finFlow: 1.1 },
    colors: {
      base: '#c8bc98',
      belly: '#e0d8b8',
      fin: '#b8ac88',
      pattern: 'lateralStripe',
      patternColor: '#2a2a2a',
      patternScale: 1.2,
      iridescence: 0.3
    },
    habitat: 'Quiet, plant-filled waters of the Amazon and Paraguay basins.',
    facts: [
      'A bold black stripe runs diagonally from its eye up to its top fin like a flag ribbon.',
      'In the wild it often swims side by side with angelfish.',
      'It loves hiding among tall plant stems and rarely bothers anyone.'
    ],
    care: 'Medium'
  },
  {
    id: 'silver_dollar',
    common: 'Silver Dollar',
    scientific: 'Metynnis argenteus',
    water: 'fresh',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 5,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'tight',
    diet: ['flake', 'pellet', 'algae'],
    price: 10,
    archetype: 'discus',
    size: 0.9,
    colors: {
      base: '#c8ccd2',
      belly: '#e4e8ec',
      fin: '#d4d8dc',
      pattern: 'none',
      patternColor: '#b0b4ba',
      patternScale: 1.0,
      iridescence: 0.8
    },
    habitat: 'Rivers of the Tapajós basin in Brazil, often among flooded plants.',
    facts: [
      'It is round and shiny like a big silver coin.',
      'It is a cousin of the piranha but only wants to eat plants and veggies.',
      'A startled school flashes silver as every fish turns at once.'
    ],
    care: 'Easy'
  },
  {
    id: 'african_butterfly_fish',
    common: 'African Butterflyfish',
    scientific: 'Pantodon buchholzi',
    water: 'fresh',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: false,
    tags: ['jumper', 'nocturnal'],
    zone: 'top',
    speed: 0.4,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 15,
    archetype: 'torpedo',
    size: 1.1,
    shape: { height: 0.9, finFlow: 1.3 },
    colors: {
      base: '#8a7a58',
      belly: '#c0b088',
      fin: '#9a8a68',
      pattern: 'patches',
      patternColor: '#4a3e28',
      patternScale: 1.3,
      iridescence: 0.2
    },
    habitat: 'Still, plant-covered pools and swamps of West and Central Africa.',
    facts: [
      'Seen from above, its big fins spread out like butterfly wings.',
      'It floats perfectly still at the surface, pretending to be a fallen leaf.',
      'It can leap from the water and glide to snatch bugs or escape danger.'
    ],
    care: 'Medium'
  },
  {
    id: 'threadfin_rainbowfish',
    common: 'Threadfin Rainbowfish',
    scientific: 'Iriatherina werneri',
    water: 'fresh',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: true,
    tags: [],
    zone: 'mid',
    speed: 0.7,
    schooling: 'loose',
    diet: ['flake', 'frozen'],
    price: 7,
    archetype: 'torpedo',
    size: 0.65,
    shape: { height: 1.1, finFlow: 1.5 },
    colors: {
      base: '#a8b0a0',
      belly: '#c8d0c0',
      fin: '#d84828',
      pattern: 'none',
      patternColor: '#88a898',
      patternScale: 1.0,
      iridescence: 0.8
    },
    habitat: 'Slow, grassy swamps and billabongs of northern Australia and New Guinea.',
    facts: [
      'Males trail long thread-like fins behind them like party streamers.',
      'It flicks its fancy fins up and down to signal to other rainbowfish.',
      'Its mouth is tiny, so it eats the smallest crumbs of food.'
    ],
    care: 'Medium'
  }
];
