export const INVERT_SPECIES_2 = [
  // ---------- FRESHWATER (12) ----------
  {
    id: 'rabbit_snail',
    common: 'Orange Rabbit Snail',
    scientific: 'Tylomelania gemmifera',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 10,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.15,
    schooling: 'solo',
    diet: ['algae', 'detritus', 'pellet'],
    edible: false,
    cleans: true,
    price: 12,
    archetype: 'snail',
    size: 1.5,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#4a3626',
      belly: '#e8862a',
      fin: '#4a3626',
      pattern: 'none',
      patternColor: '#2c2015',
      patternScale: 1.0,
      iridescence: 0.05
    },
    habitat: 'Ancient deep lakes on the island of Sulawesi in Indonesia.',
    facts: [
      'Its long droopy snout and wrinkly orange face make it look just like a little bunny rabbit.',
      'Instead of laying lots of eggs, the mother releases one baby at a time, wrapped in a milky white pearl.',
      'It plows its snout through the sand like a tiny vacuum cleaner, hunting for tasty bits.'
    ],
    care: 'Medium'
  },
  {
    id: 'black_devil_snail',
    common: 'Black Devil Snail',
    scientific: 'Faunus ater',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.15,
    schooling: 'solo',
    diet: ['algae', 'detritus'],
    edible: false,
    cleans: true,
    price: 8,
    archetype: 'snail',
    size: 1.4,
    shape: { height: 1.5, finFlow: 1.0 },
    colors: {
      base: '#1c1714',
      belly: '#5a5048',
      fin: '#1c1714',
      pattern: 'none',
      patternColor: '#0d0a08',
      patternScale: 1.0,
      iridescence: 0.15
    },
    habitat: 'Slow rivers and estuaries of Southeast Asia close to the sea.',
    facts: [
      'Its long pointy shell is shiny jet black all over, like it is carved from licorice.',
      'Despite its spooky name it is one of the gentlest snails and never bothers anyone.',
      'In the wild it lives where rivers meet the ocean, so it does not mind a little salt in its water.'
    ],
    care: 'Easy'
  },
  {
    id: 'horned_nerite_snail',
    common: 'Horned Nerite Snail',
    scientific: 'Clithon corona',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 1.5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'glass',
    speed: 0.15,
    schooling: 'solo',
    diet: ['algae'],
    edible: false,
    cleans: true,
    price: 4,
    archetype: 'snail',
    size: 0.6,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#e0c23c',
      belly: '#b0a48c',
      fin: '#e0c23c',
      pattern: 'stripesH',
      patternColor: '#241a10',
      patternScale: 1.3,
      iridescence: 0.05
    },
    habitat: 'Streams and river mouths of Southeast Asia and the Pacific islands.',
    facts: [
      'Its striped shell grows real pointy horns, like a teeny tiny dragon riding around the tank.',
      'The horns make it hard for hungry fish to swallow, so most fish leave it alone.',
      'Even though it is smaller than a jellybean, it scrubs algae all day like a busy janitor.'
    ],
    care: 'Easy'
  },
  {
    id: 'japanese_trapdoor_snail',
    common: 'Japanese Trapdoor Snail',
    scientific: 'Cipangopaludina japonica',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 5,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['coldwater'],
    zone: 'bottom',
    speed: 0.15,
    schooling: 'solo',
    diet: ['algae', 'detritus', 'pellet'],
    edible: false,
    cleans: true,
    price: 5,
    archetype: 'snail',
    size: 1.3,
    shape: { height: 1.2, finFlow: 1.0 },
    colors: {
      base: '#6a5a40',
      belly: '#a89878',
      fin: '#6a5a40',
      pattern: 'none',
      patternColor: '#3e3220',
      patternScale: 1.0,
      iridescence: 0.05
    },
    habitat: 'Cool ponds, rice paddies, and slow rivers of Japan and eastern Asia.',
    facts: [
      'It carries a round trapdoor on its foot and pulls it shut like a front door when it hides.',
      'Mothers do not lay eggs at all; their babies are born as perfect little snails ready to crawl.',
      'It is so tough it can snooze through winter at the bottom of an icy pond.'
    ],
    care: 'Easy'
  },
  {
    id: 'crystal_red_shrimp',
    common: 'Crystal Red Shrimp',
    scientific: 'Caridina cantonensis',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 2.5,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.35,
    schooling: 'loose',
    diet: ['algae', 'detritus', 'flake'],
    edible: true,
    cleans: true,
    price: 10,
    archetype: 'shrimp',
    size: 0.8,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#f0ede6',
      belly: '#f7f5f0',
      fin: '#f0ede6',
      pattern: 'stripesV',
      patternColor: '#c81f1f',
      patternScale: 1.2,
      iridescence: 0.25
    },
    habitat: 'Cool, clean mountain streams of southern China and Taiwan.',
    facts: [
      'Its bright red and snow-white bands make it look like a swimming candy cane.',
      'It was created in Japan when a shrimp keeper found one lucky red shrimp and raised its babies.',
      'Shrimp keepers grade them like sparkly gems, and the whitest ones win prizes.'
    ],
    care: 'Medium'
  },
  {
    id: 'blue_velvet_shrimp',
    common: 'Blue Velvet Shrimp',
    scientific: 'Neocaridina davidi',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 2.5,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.35,
    schooling: 'loose',
    diet: ['algae', 'detritus', 'flake'],
    edible: true,
    cleans: true,
    price: 6,
    archetype: 'shrimp',
    size: 0.8,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#2f5fc4',
      belly: '#6a8fd8',
      fin: '#2f5fc4',
      pattern: 'none',
      patternColor: '#1c3a80',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Slow plant-filled streams and ponds of Taiwan and southern China.',
    facts: [
      'It is the cherry shrimp’s cousin, the very same kind of shrimp wearing a bright blue suit.',
      'People picked the bluest shrimp parents again and again until their babies shone like the summer sky.',
      'Its front feet work like tiny tweezers, picking up crumbs far too small for you to see.'
    ],
    care: 'Easy'
  },
  {
    id: 'green_babaulti_shrimp',
    common: 'Green Babaulti Shrimp',
    scientific: 'Caridina babaulti',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 3,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.35,
    schooling: 'loose',
    diet: ['algae', 'detritus', 'flake'],
    edible: true,
    cleans: true,
    price: 6,
    archetype: 'shrimp',
    size: 0.9,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#4a8f2e',
      belly: '#7ab85a',
      fin: '#4a8f2e',
      pattern: 'none',
      patternColor: '#2e5c1c',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Weedy slow-moving rivers of India with lots of fallen leaves.',
    facts: [
      'It is leaf-green from nose to tail, so it can vanish among the plants like a ninja.',
      'It can slowly change its shade of green over a few days to match its home.',
      'Its nose spike is extra long and pointy, like a little green swordfish of the shrimp world.'
    ],
    care: 'Easy'
  },
  {
    id: 'snowball_shrimp',
    common: 'Snowball Shrimp',
    scientific: 'Neocaridina zhangjiajiensis',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 2.5,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.35,
    schooling: 'loose',
    diet: ['algae', 'detritus', 'flake'],
    edible: true,
    cleans: true,
    price: 5,
    archetype: 'shrimp',
    size: 0.8,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#eef2f0',
      belly: '#f8faf9',
      fin: '#eef2f0',
      pattern: 'none',
      patternColor: '#cfd8d4',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Clear streams and pools of central China.',
    facts: [
      'It is frosty white all over, like a tiny snowball scooting around the tank.',
      'A mother carries eggs that look like a bundle of mini snowballs, which is how it got its name.',
      'Like all shrimp it wears its skeleton on the outside and swaps it for a bigger one as it grows.'
    ],
    care: 'Easy'
  },
  {
    id: 'thai_micro_crab',
    common: 'Thai Micro Crab',
    scientific: 'Limnopilos naiyanetri',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 1,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.25,
    schooling: 'loose',
    diet: ['detritus', 'algae', 'flake'],
    edible: true,
    cleans: true,
    price: 8,
    archetype: 'crab',
    size: 0.6,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#9a938a',
      belly: '#c4beb5',
      fin: '#9a938a',
      pattern: 'none',
      patternColor: '#6b655c',
      patternScale: 1.0,
      iridescence: 0.1
    },
    habitat: 'Roots of floating water hyacinth plants in one river in Thailand.',
    facts: [
      'It is one of the smallest crabs in the whole world, tiny enough to sit on your pinky fingernail.',
      'Its legs are covered in fuzzy little hairs that catch floating crumbs like a net.',
      'Wild ones have only ever been found in a single river in Thailand, hiding in plant roots.'
    ],
    care: 'Medium'
  },
  {
    id: 'freshwater_pom_pom_crab',
    common: 'Freshwater Pom Pom Crab',
    scientific: 'Ptychognathus barbatus',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 2.5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['detritus', 'algae', 'pellet'],
    edible: true,
    cleans: true,
    price: 9,
    archetype: 'crab',
    size: 0.8,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#b09a6a',
      belly: '#d6c69e',
      fin: '#b09a6a',
      pattern: 'spots',
      patternColor: '#6e5c38',
      patternScale: 0.8,
      iridescence: 0.05
    },
    habitat: 'Sandy river mouths of Taiwan and islands of the western Pacific.',
    facts: [
      'The boys grow fluffy fur pom-poms on their claws, like a cheerleader ready for the big game.',
      'Unlike most little crabs it is happy living underwater all the time and never needs dry land.',
      'It scuttles sideways from hideout to hideout, tidying up crumbs as it goes.'
    ],
    care: 'Easy'
  },
  {
    id: 'cajun_dwarf_crayfish',
    common: 'Cajun Dwarf Crayfish',
    scientific: 'Cambarellus shufeldtii',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 3,
    bioload: 1,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['pellet', 'detritus', 'frozen'],
    edible: true,
    cleans: true,
    price: 6,
    archetype: 'crayfish',
    size: 0.7,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#8a5a3a',
      belly: '#b8906a',
      fin: '#8a5a3a',
      pattern: 'stripesH',
      patternColor: '#4e3018',
      patternScale: 1.1,
      iridescence: 0.05
    },
    habitat: 'Swamps, ditches, and bayous of Louisiana and the Mississippi River valley.',
    facts: [
      'It is a real crayfish no bigger than a paperclip, with racing stripes down its back.',
      'It comes from the bayous of Louisiana, splashing around where alligators live.',
      'It waves its tiny claws at anything that gets too close, even fish ten times its size.'
    ],
    care: 'Easy'
  },
  {
    id: 'electric_blue_crayfish',
    common: 'Electric Blue Crayfish',
    scientific: 'Procambarus alleni',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 12,
    bioload: 3,
    minSchool: 1,
    temperament: 'aggressive',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['pellet', 'detritus', 'frozen'],
    edible: false,
    cleans: true,
    price: 20,
    archetype: 'crayfish',
    size: 1.5,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#1e4fd0',
      belly: '#5a80e0',
      fin: '#1e4fd0',
      pattern: 'spots',
      patternColor: '#e8ecf5',
      patternScale: 0.7,
      iridescence: 0.2
    },
    habitat: 'Marshes and flooded grasslands of the Florida Everglades.',
    facts: [
      'Wild ones are often brownish, but the bluest were raised together until they glowed like superheroes.',
      'In the Everglades dry season it digs a deep burrow and waits underground for the rains to return.',
      'It walks forward on its legs but escapes backward, zooming away with a big flip of its tail.'
    ],
    care: 'Medium'
  },

  // ---------- SALTWATER (12) ----------
  {
    id: 'cerith_snail',
    common: 'Cerith Snail',
    scientific: 'Cerithium litteratum',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 2.5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.15,
    schooling: 'solo',
    diet: ['algae', 'detritus'],
    edible: false,
    cleans: true,
    price: 2,
    archetype: 'snail',
    size: 0.7,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#d8cbb2',
      belly: '#ece3d2',
      fin: '#d8cbb2',
      pattern: 'spots',
      patternColor: '#5c4a32',
      patternScale: 0.8,
      iridescence: 0.05
    },
    habitat: 'Sandy shallows and seagrass beds of the Caribbean Sea.',
    facts: [
      'It works the night shift, popping out of the sand after dark to clean up while the fish sleep.',
      'Its pointy spiral shell lets it dive under the sand and pop back up like a submarine.',
      'It draws its eggs on the glass in long squiggly white spirals, like tiny frosting doodles.'
    ],
    care: 'Easy'
  },
  {
    id: 'banded_trochus_snail',
    common: 'Banded Trochus Snail',
    scientific: 'Trochus histrio',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 2.5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'glass',
    speed: 0.15,
    schooling: 'solo',
    diet: ['algae'],
    edible: false,
    cleans: true,
    price: 4,
    archetype: 'snail',
    size: 0.9,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#c8b8a0',
      belly: '#e0d6c4',
      fin: '#c8b8a0',
      pattern: 'stripesH',
      patternColor: '#a03a2e',
      patternScale: 1.2,
      iridescence: 0.1
    },
    habitat: 'Rocky reef flats of the warm Indo-Pacific ocean.',
    facts: [
      'Its shell is shaped just like a spinning top with red-and-cream stripes winding around it.',
      'If it gets knocked over it can flip itself right back up, a trick most snails cannot do.',
      'Happy trochus snails sometimes have babies right in the aquarium, dusting the glass with mini snails.'
    ],
    care: 'Easy'
  },
  {
    id: 'bumble_bee_snail',
    common: 'Bumble Bee Snail',
    scientific: 'Engina mendicaria',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 1.5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.15,
    schooling: 'solo',
    diet: ['detritus', 'frozen'],
    edible: false,
    cleans: true,
    price: 3,
    archetype: 'snail',
    size: 0.6,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#f2c93c',
      belly: '#e8dcb8',
      fin: '#f2c93c',
      pattern: 'stripesH',
      patternColor: '#1c1812',
      patternScale: 1.3,
      iridescence: 0.05
    },
    habitat: 'Rocky shores and reef rubble of the Indian and Pacific Oceans.',
    facts: [
      'It is striped black and yellow just like a bumblebee, but it lives underwater and cannot sting.',
      'It is only the size of a pea, one of the smallest helpers you can add to a reef tank.',
      'It pokes through the sand like a tiny detective, sniffing out leftover crumbs to gobble up.'
    ],
    care: 'Easy'
  },
  {
    id: 'sexy_shrimp',
    common: 'Sexy Shrimp',
    scientific: 'Thor amboinensis',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 1.5,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'loose',
    diet: ['frozen', 'flake', 'detritus'],
    edible: true,
    cleans: true,
    price: 12,
    archetype: 'shrimp',
    size: 0.6,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#a86a32',
      belly: '#c99a5e',
      fin: '#a86a32',
      pattern: 'spots',
      patternColor: '#f5f0e0',
      patternScale: 1.3,
      iridescence: 0.2
    },
    habitat: 'Anemones on shallow coral reefs in warm seas all around the world.',
    facts: [
      'It holds its tail high in the air and wiggles it as it walks, a silly dance that gave it its name.',
      'It lives right on top of stinging anemones without getting hurt, like sleeping on a bed of nettles.',
      'It is so tiny that three of them could stand together on a single coin.'
    ],
    care: 'Medium'
  },
  {
    id: 'harlequin_shrimp',
    common: 'Harlequin Shrimp',
    scientific: 'Hymenocera picta',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['expertDiet'],
    zone: 'bottom',
    speed: 0.25,
    schooling: 'solo',
    diet: ['frozen'],
    edible: true,
    cleans: false,
    price: 45,
    archetype: 'shrimp',
    size: 0.9,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#f0ece2',
      belly: '#f7f4ec',
      fin: '#f0ece2',
      pattern: 'spots',
      patternColor: '#7a4aa0',
      patternScale: 1.6,
      iridescence: 0.2
    },
    habitat: 'Coral rubble crevices on reefs of the Indian and Pacific Oceans.',
    facts: [
      'It looks painted, creamy white splashed with big blue-purple spots like an artist got carried away.',
      'Its giant flat claws look like flower petals, and it waves them slowly as it walks.',
      'It almost always lives with a partner, and the pair does everything side by side as a team.'
    ],
    care: 'Hard'
  },
  {
    id: 'coral_banded_shrimp',
    common: 'Coral Banded Shrimp',
    scientific: 'Stenopus hispidus',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 6,
    bioload: 1,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'detritus'],
    edible: false,
    cleans: true,
    price: 15,
    archetype: 'shrimp',
    size: 1.2,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#e8e2d6',
      belly: '#f2eee4',
      fin: '#e8e2d6',
      pattern: 'stripesV',
      patternColor: '#c22b1e',
      patternScale: 1.3,
      iridescence: 0.2
    },
    habitat: 'Reef caves and overhangs in warm seas all around the world.',
    facts: [
      'It is striped red and white like a barber pole, with long arms it holds out like a knight.',
      'If it loses one of its big arms in a scuffle, it simply grows a brand new one.',
      'It hangs upside down under ledges and waves its long white antennae to say hello.'
    ],
    care: 'Easy'
  },
  {
    id: 'sally_lightfoot_crab',
    common: 'Sally Lightfoot Crab',
    scientific: 'Percnon gibbesi',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.5,
    schooling: 'solo',
    diet: ['algae', 'detritus', 'pellet'],
    edible: false,
    cleans: true,
    price: 12,
    archetype: 'crab',
    size: 1.1,
    shape: { height: 0.8, finFlow: 1.0 },
    colors: {
      base: '#5a5238',
      belly: '#8a8060',
      fin: '#c9862a',
      pattern: 'stripesH',
      patternColor: '#c9862a',
      patternScale: 0.9,
      iridescence: 0.1
    },
    habitat: 'Wave-splashed rocks and reef edges of the Caribbean and tropical Atlantic.',
    facts: [
      'It is named after a dancer because it is one of the fastest, lightest-footed crabs in the sea.',
      'Its body is flat as a pancake so it can slip into cracks too thin for anything to follow.',
      'Each leg wears bright orange rings, like it pulled on stripy socks before coming out.'
    ],
    care: 'Easy'
  },
  {
    id: 'blue_leg_hermit_crab',
    common: 'Blue Leg Hermit Crab',
    scientific: 'Clibanarius tricolor',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 2,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.25,
    schooling: 'loose',
    diet: ['algae', 'detritus', 'pellet'],
    edible: false,
    cleans: true,
    price: 3,
    archetype: 'crab',
    size: 0.6,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#2f5fc4',
      belly: '#7a95d8',
      fin: '#2f5fc4',
      pattern: 'stripesH',
      patternColor: '#e8e2d0',
      patternScale: 0.9,
      iridescence: 0.1
    },
    habitat: 'Shallow reefs and tide pools of the Caribbean Sea.',
    facts: [
      'Its little legs are bright blue with white bands, poking out of a borrowed snail shell house.',
      'When it outgrows its shell it tries on empty ones like shoes until it finds the perfect fit.',
      'It is a champion tank cleaner, nibbling algae and crumbs all day without a break.'
    ],
    care: 'Easy'
  },
  {
    id: 'halloween_hermit_crab',
    common: 'Halloween Hermit Crab',
    scientific: 'Ciliopagurus strigatus',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 5,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.25,
    schooling: 'solo',
    diet: ['algae', 'detritus', 'pellet'],
    edible: false,
    cleans: true,
    price: 12,
    archetype: 'crab',
    size: 0.9,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#e05a1e',
      belly: '#f2a05e',
      fin: '#e05a1e',
      pattern: 'stripesH',
      patternColor: '#b01c14',
      patternScale: 1.2,
      iridescence: 0.1
    },
    habitat: 'Coral reefs and lagoons of the Indo-Pacific, from Hawaii to the Red Sea.',
    facts: [
      'Its legs wear bold orange and red stripes, like it dressed up for Halloween all year long.',
      'Its body is flat, so it likes to live in the long thin shells of cone snails instead of round ones.',
      'It bulldozes across the sand while it cleans, stirring the whole sandbed like a tiny tractor.'
    ],
    care: 'Easy'
  },
  {
    id: 'tuxedo_urchin',
    common: 'Blue Tuxedo Urchin',
    scientific: 'Mespilia globulus',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 5,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.15,
    schooling: 'solo',
    diet: ['algae'],
    edible: false,
    cleans: true,
    price: 14,
    archetype: 'urchin',
    size: 1.0,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#8a4a2e',
      belly: '#3a55a8',
      fin: '#8a4a2e',
      pattern: 'stripesV',
      patternColor: '#3a55a8',
      patternScale: 1.2,
      iridescence: 0.2
    },
    habitat: 'Rubble patches on coral reefs of the western Pacific Ocean.',
    facts: [
      'Between its rows of spines run bands of velvety blue, like it is wearing a fancy tuxedo.',
      'It picks up shells, pebbles, and bits of seaweed and carries them on its head like a hat.',
      'Hundreds of tiny suction-cup feet hide between its spines and pull it slowly along.'
    ],
    care: 'Medium'
  },
  {
    id: 'banded_brittle_star',
    common: 'Banded Brittle Star',
    scientific: 'Ophiolepis superba',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 20,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['detritus', 'frozen'],
    edible: false,
    cleans: true,
    price: 15,
    archetype: 'star',
    size: 1.3,
    shape: { height: 0.8, finFlow: 1.0 },
    colors: {
      base: '#c8a86a',
      belly: '#e0cba0',
      fin: '#c8a86a',
      pattern: 'stripesH',
      patternColor: '#4a3220',
      patternScale: 1.2,
      iridescence: 0.05
    },
    habitat: 'Under rocks and coral rubble on reefs of the Indo-Pacific ocean.',
    facts: [
      'Its five stripy arms wiggle like snakes, making it surprisingly speedy for a starfish cousin.',
      'If an arm snaps off it grows a whole new one, which is why it is called brittle.',
      'It hides under rocks all day with just an arm or two poking out, feeling around for crumbs.'
    ],
    care: 'Medium'
  },
  {
    id: 'rock_flower_anemone',
    common: 'Rock Flower Anemone',
    scientific: 'Phymanthus crucifer',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'fixed',
    speed: 0,
    schooling: 'solo',
    diet: ['frozen'],
    edible: false,
    cleans: false,
    price: 25,
    archetype: 'anemone',
    size: 0.9,
    shape: { height: 0.8, finFlow: 1.2 },
    colors: {
      base: '#2a8a7a',
      belly: '#5ab0a0',
      fin: '#d84a3a',
      pattern: 'none',
      patternColor: '#d84a3a',
      patternScale: 1.0,
      iridescence: 0.25
    },
    habitat: 'Rocky rubble and crevices on shallow reefs of the Caribbean Sea.',
    facts: [
      'It comes in almost every color mix you can imagine, and like snowflakes no two look alike.',
      'It tucks its body into a crack in the rocks so only its flower face peeks out.',
      'Its sticky tentacles catch bits of food and pass them to the mouth hiding in the middle.'
    ],
    care: 'Medium'
  }
];
