export const INVERT_SPECIES = [
  // ---------- FRESHWATER (10) ----------
  {
    id: 'cherry_shrimp',
    common: 'Cherry Shrimp',
    scientific: 'Neocaridina davidi',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 2.5,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.35,
    schooling: 'loose',
    diet: ['algae', 'detritus', 'flake'],
    edible: true,
    cleans: true,
    price: 4,
    archetype: 'shrimp',
    size: 0.8,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#d61f1f',
      belly: '#e8574f',
      fin: '#d61f1f',
      pattern: 'none',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.25
    },
    habitat: 'Slow streams and ponds of Taiwan with lots of plants and leaf litter.',
    facts: [
      'When a cherry shrimp grows, it climbs out of its old shell and leaves a see-through ghost suit behind.',
      'A mother shrimp carries her eggs under her tail and fans them with her little legs to keep them clean.',
      'Wild cherry shrimp are brownish, but people bred the brightest red ones together to make them this cherry color.'
    ],
    care: 'Easy'
  },
  {
    id: 'amano_shrimp',
    common: 'Amano Shrimp',
    scientific: 'Caridina multidentata',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.4,
    schooling: 'loose',
    diet: ['algae', 'detritus', 'pellet'],
    edible: true,
    cleans: true,
    price: 5,
    archetype: 'shrimp',
    size: 1.1,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#9aa88f',
      belly: '#c9d2c0',
      fin: '#9aa88f',
      pattern: 'spots',
      patternColor: '#6b5a3e',
      patternScale: 0.8,
      iridescence: 0.2
    },
    habitat: 'Cool hillside streams of Japan and Taiwan that flow down to the sea.',
    facts: [
      'It is one of the best algae eaters in the world and busily picks at plants all day like a tiny gardener.',
      'Its body is almost see-through with a line of little dots and dashes down each side.',
      'Baby amano shrimp must drift down rivers to the salty sea to grow up, then march back to fresh water.'
    ],
    care: 'Easy'
  },
  {
    id: 'ghost_shrimp',
    common: 'Ghost Shrimp',
    scientific: 'Palaemonetes paludosus',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.45,
    schooling: 'loose',
    diet: ['detritus', 'flake', 'algae'],
    edible: true,
    cleans: true,
    price: 1,
    archetype: 'shrimp',
    size: 1.0,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#cfd8d4',
      belly: '#e6ece9',
      fin: '#cfd8d4',
      pattern: 'none',
      patternColor: '#888888',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Weedy ponds, ditches, and slow rivers of the southeastern United States.',
    facts: [
      'Its body is so clear you can watch the food travel through its tummy after it eats.',
      'Being see-through is its superpower, because hungry fish look right past it.',
      'When it is scared it flicks its tail and shoots backwards like a tiny rocket.'
    ],
    care: 'Easy'
  },
  {
    id: 'nerite_snail',
    common: 'Zebra Nerite Snail',
    scientific: 'Neritina natalensis',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 2.5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'glass',
    speed: 0.15,
    schooling: 'solo',
    diet: ['algae'],
    edible: false,
    cleans: true,
    price: 3,
    archetype: 'snail',
    size: 0.9,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#d8a531',
      belly: '#b0a48c',
      fin: '#d8a531',
      pattern: 'stripesH',
      patternColor: '#2a1f14',
      patternScale: 1.2,
      iridescence: 0.1
    },
    habitat: 'Rivers and streams of eastern Africa near where they meet the sea.',
    facts: [
      'Its shell has bold black and gold stripes like a tiny zebra riding on its back.',
      'It scrapes algae off the glass with a raspy tongue covered in thousands of tiny teeth.',
      'Its eggs never hatch in a freshwater tank, because the babies need salty water to grow.'
    ],
    care: 'Easy'
  },
  {
    id: 'mystery_snail',
    common: 'Gold Mystery Snail',
    scientific: 'Pomacea bridgesii',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'glass',
    speed: 0.2,
    schooling: 'solo',
    diet: ['algae', 'pellet', 'detritus'],
    edible: false,
    cleans: true,
    price: 4,
    archetype: 'snail',
    size: 1.3,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#f2b636',
      belly: '#f7d98a',
      fin: '#f2b636',
      pattern: 'none',
      patternColor: '#a87614',
      patternScale: 1.0,
      iridescence: 0.1
    },
    habitat: 'Slow rivers, swamps, and flooded meadows of South America.',
    facts: [
      'It has a built-in snorkel tube it stretches up to the surface to take a breath of air.',
      'A mother mystery snail crawls above the water at night to lay a pink bunch of eggs where fish cannot reach.',
      'If something startles it, it pulls inside its shell and slams a little trapdoor shut behind it.'
    ],
    care: 'Easy'
  },
  {
    id: 'dwarf_crayfish',
    common: 'Dwarf Orange Crayfish',
    scientific: 'Cambarellus patzcuarensis',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['pellet', 'detritus', 'frozen'],
    edible: true,
    cleans: true,
    price: 8,
    archetype: 'crayfish',
    size: 0.8,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#e8802a',
      belly: '#f2a95e',
      fin: '#e8802a',
      pattern: 'none',
      patternColor: '#b35a10',
      patternScale: 1.0,
      iridescence: 0.1
    },
    habitat: 'Lake Patzcuaro and its cool spring-fed streams in the mountains of Mexico.',
    facts: [
      'It looks like a tiny lobster but stays small enough to sit on a grown-up thumb.',
      'It holds its little claws up in the air to say "I am big and tough!" even though it is tiny.',
      'If it loses a claw in a squabble, it simply grows a brand new one the next time it molts.'
    ],
    care: 'Medium'
  },
  {
    id: 'assassin_snail',
    common: 'Assassin Snail',
    scientific: 'Anentome helena',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 2.5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.15,
    schooling: 'solo',
    diet: ['detritus', 'frozen', 'pellet'],
    edible: false,
    cleans: true,
    price: 3,
    archetype: 'snail',
    size: 0.9,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#e0b53c',
      belly: '#c9b98f',
      fin: '#e0b53c',
      pattern: 'stripesH',
      patternColor: '#3b2a14',
      patternScale: 1.3,
      iridescence: 0.05
    },
    habitat: 'Sandy streams and lakes of Southeast Asia, from Thailand to Indonesia.',
    facts: [
      'Its shell is striped yellow and brown like a little bumblebee.',
      'Fish keepers love it because it hunts pest snails and keeps them from taking over the tank.',
      'It hides under the sand with just its snorkel poking out, waiting patiently like a secret agent.'
    ],
    care: 'Easy'
  },
  {
    id: 'ramshorn_snail',
    common: 'Red Ramshorn Snail',
    scientific: 'Planorbella duryi',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 2,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'glass',
    speed: 0.2,
    schooling: 'solo',
    diet: ['algae', 'detritus', 'flake'],
    edible: false,
    cleans: true,
    price: 2,
    archetype: 'snail',
    size: 0.7,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#b8402a',
      belly: '#d4705a',
      fin: '#b8402a',
      pattern: 'none',
      patternColor: '#7a2314',
      patternScale: 1.0,
      iridescence: 0.05
    },
    habitat: 'Warm ponds, marshes, and slow canals of Florida in the United States.',
    facts: [
      'Its flat coiled shell looks just like the curly horn of a ram, which is how it got its name.',
      'It is red because its blood is red like ours, which is very unusual for a snail.',
      'It breathes air, so it glides up to the surface like a tiny elevator when it needs a breath.'
    ],
    care: 'Easy'
  },
  {
    id: 'bamboo_shrimp',
    common: 'Bamboo Shrimp',
    scientific: 'Atyopsis moluccensis',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.25,
    schooling: 'solo',
    diet: ['detritus', 'flake'],
    edible: true,
    cleans: true,
    price: 12,
    archetype: 'shrimp',
    size: 1.5,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#a5502e',
      belly: '#d1a179',
      fin: '#a5502e',
      pattern: 'lateralStripe',
      patternColor: '#e8d2a8',
      patternScale: 1.0,
      iridescence: 0.15
    },
    habitat: 'Fast-flowing rocky streams of Southeast Asia, from Thailand to Indonesia.',
    facts: [
      'Instead of claws it has four feathery fans on its hands that it opens to catch food floating by.',
      'It climbs to the spot with the strongest current and stands there like it is catching snowflakes.',
      'When a fan gets full, it swipes it across its mouth like licking food off a mitten.'
    ],
    care: 'Medium'
  },
  {
    id: 'malaysian_trumpet_snail',
    common: 'Malaysian Trumpet Snail',
    scientific: 'Melanoides tuberculata',
    water: 'fresh',
    kind: 'invert',
    adultSizeCm: 2,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.15,
    schooling: 'solo',
    diet: ['detritus', 'algae'],
    edible: false,
    cleans: true,
    price: 1,
    archetype: 'snail',
    size: 0.7,
    shape: { height: 1.4, finFlow: 1.0 },
    colors: {
      base: '#8a7a5c',
      belly: '#b3a687',
      fin: '#8a7a5c',
      pattern: 'spots',
      patternColor: '#5a4630',
      patternScale: 0.7,
      iridescence: 0.05
    },
    habitat: 'Muddy and sandy bottoms of warm rivers and lakes across Asia and Africa.',
    facts: [
      'Its shell is a long pointy spiral, like a tiny ice cream cone or trumpet.',
      'It spends all day buried in the sand and pops out at night, stirring the sand and keeping it healthy.',
      'Mothers do not lay eggs; the babies ride inside her and come out as perfect mini snails.'
    ],
    care: 'Easy'
  },

  // ---------- SALTWATER (10) ----------
  {
    id: 'skunk_cleaner_shrimp',
    common: 'Skunk Cleaner Shrimp',
    scientific: 'Lysmata amboinensis',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.4,
    schooling: 'loose',
    diet: ['frozen', 'pellet', 'detritus'],
    edible: false,
    cleans: true,
    price: 30,
    archetype: 'shrimp',
    size: 1.1,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#c9502e',
      belly: '#e8b56a',
      fin: '#c9502e',
      pattern: 'lateralStripe',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.25
    },
    habitat: 'Coral reef caves and ledges across the Indian and Pacific Oceans.',
    facts: [
      'It runs a cleaning station where big fish line up and wait their turn, like a car wash for fish.',
      'Fish open their mouths wide and let it climb right inside to pick food from their teeth, and nobody gets eaten.',
      'It waves its long white antennae like flags to tell passing fish "the cleaner is open!"'
    ],
    care: 'Medium'
  },
  {
    id: 'peppermint_shrimp',
    common: 'Peppermint Shrimp',
    scientific: 'Lysmata wurdemanni',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.4,
    schooling: 'loose',
    diet: ['frozen', 'pellet', 'detritus'],
    edible: true,
    cleans: true,
    price: 15,
    archetype: 'shrimp',
    size: 0.9,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#d8a08c',
      belly: '#ecd0c4',
      fin: '#d8a08c',
      pattern: 'stripesH',
      patternColor: '#b03a2e',
      patternScale: 1.2,
      iridescence: 0.2
    },
    habitat: 'Rocky crevices and pier pilings along the Caribbean Sea and Gulf of Mexico.',
    facts: [
      'Its clear body has thin red candy-cane stripes, which is why it is named after peppermint.',
      'Aquarium keepers love it because it gobbles up pesky stinging anemones called aiptasia.',
      'It is shy in the daytime and creeps out at night to tidy up leftover food.'
    ],
    care: 'Medium'
  },
  {
    id: 'fire_shrimp',
    common: 'Blood Red Fire Shrimp',
    scientific: 'Lysmata debelius',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'detritus'],
    edible: false,
    cleans: true,
    price: 40,
    archetype: 'shrimp',
    size: 1.1,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#b31217',
      belly: '#c93a3a',
      fin: '#b31217',
      pattern: 'spots',
      patternColor: '#ffffff',
      patternScale: 0.9,
      iridescence: 0.3
    },
    habitat: 'Deep, dark reef caves of the Indian Ocean and western Pacific.',
    facts: [
      'It is one of the reddest animals in the ocean, deep fire-engine red with tiny white polka dots.',
      'It is a cleaner shrimp too, so fish let it tiptoe over them and pick off itchy pests.',
      'It loves dim caves, so you mostly see its long white antennae poking out of its hideout.'
    ],
    care: 'Medium'
  },
  {
    id: 'scarlet_hermit_crab',
    common: 'Scarlet Reef Hermit Crab',
    scientific: 'Paguristes cadenati',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 3,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.25,
    schooling: 'loose',
    diet: ['algae', 'detritus', 'pellet'],
    edible: false,
    cleans: true,
    price: 6,
    archetype: 'crab',
    size: 0.8,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#c22b1e',
      belly: '#d96a4a',
      fin: '#c22b1e',
      pattern: 'none',
      patternColor: '#f5d547',
      patternScale: 1.0,
      iridescence: 0.1
    },
    habitat: 'Shallow coral reefs of the Caribbean Sea and the Florida Keys.',
    facts: [
      'It has bright red legs and yellow eyestalks, like it is wearing a red suit with yellow periscopes.',
      'It does not grow its own shell; it borrows an empty snail shell and carries its house everywhere.',
      'When it gets too big for its shell, it hunts for a roomier one and moves in with a quick hop.'
    ],
    care: 'Easy'
  },
  {
    id: 'emerald_crab',
    common: 'Emerald Crab',
    scientific: 'Mithraculus sculptus',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 5,
    bioload: 2,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.25,
    schooling: 'solo',
    diet: ['algae', 'detritus', 'pellet'],
    edible: false,
    cleans: true,
    price: 10,
    archetype: 'crab',
    size: 1.0,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#2e7d4f',
      belly: '#5aa878',
      fin: '#2e7d4f',
      pattern: 'none',
      patternColor: '#1c4d30',
      patternScale: 1.0,
      iridescence: 0.15
    },
    habitat: 'Rubble and coral heads on shallow reefs of the Caribbean Sea.',
    facts: [
      'It is shiny green like a little emerald jewel scuttling around the rocks.',
      'It is famous for eating bubble algae, a green pest that looks like tiny grapes.',
      'Its claws have spoon-shaped tips, perfect for scooping algae off the rocks like ice cream.'
    ],
    care: 'Easy'
  },
  {
    id: 'turbo_snail',
    common: 'Mexican Turbo Snail',
    scientific: 'Turbo fluctuosus',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 5,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'glass',
    speed: 0.2,
    schooling: 'solo',
    diet: ['algae'],
    edible: false,
    cleans: true,
    price: 4,
    archetype: 'snail',
    size: 1.3,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#8c7f6a',
      belly: '#c2b49a',
      fin: '#8c7f6a',
      pattern: 'spots',
      patternColor: '#4f4536',
      patternScale: 0.9,
      iridescence: 0.1
    },
    habitat: 'Rocky shores of the Gulf of California along the coast of Mexico.',
    facts: [
      'Despite the racecar name, it is a slow and steady algae-mowing machine.',
      'One turbo snail can polish a whole pane of aquarium glass sparkling clean overnight.',
      'It carries a round trapdoor on its foot and seals itself inside its shell when danger comes.'
    ],
    care: 'Easy'
  },
  {
    id: 'nassarius_snail',
    common: 'Nassarius Snail',
    scientific: 'Nassarius vibex',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 2,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.3,
    schooling: 'loose',
    diet: ['detritus', 'frozen'],
    edible: false,
    cleans: true,
    price: 2,
    archetype: 'snail',
    size: 0.7,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#c8b48e',
      belly: '#e2d6ba',
      fin: '#c8b48e',
      pattern: 'spots',
      patternColor: '#6e5a3c',
      patternScale: 0.8,
      iridescence: 0.05
    },
    habitat: 'Sandy and muddy sea floors along the western Atlantic coast.',
    facts: [
      'It hides under the sand with a long snorkel sticking up like a periscope.',
      'The moment food touches the water it can smell it, and the sand erupts with speeding snails.',
      'For a snail it is surprisingly fast, plowing through the sand like a tiny snowplow.'
    ],
    care: 'Easy'
  },
  {
    id: 'bubble_tip_anemone',
    common: 'Bubble-Tip Anemone',
    scientific: 'Entacmaea quadricolor',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 25,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['hostsAnemone'],
    zone: 'fixed',
    speed: 0,
    schooling: 'solo',
    diet: ['frozen'],
    edible: false,
    cleans: false,
    price: 45,
    archetype: 'anemone',
    size: 1.4,
    shape: { height: 1.0, finFlow: 1.3 },
    colors: {
      base: '#8a3b6b',
      belly: '#a85e88',
      fin: '#c96a2a',
      pattern: 'none',
      patternColor: '#c96a2a',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Sunny coral reefs of the Indian and Pacific Oceans, tucked into rock crevices.',
    facts: [
      'Its tentacles puff up into little bubbles at the tips, like a bouquet of balloons.',
      'Clownfish snuggle into it for safety, because its sting does not hurt them.',
      'When it wants more anemone friends, it can split itself right down the middle and become two.'
    ],
    care: 'Hard'
  },
  {
    id: 'feather_duster_worm',
    common: 'Feather Duster Worm',
    scientific: 'Sabellastarte spectabilis',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 10,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'fixed',
    speed: 0,
    schooling: 'solo',
    diet: ['detritus'],
    edible: false,
    cleans: true,
    price: 15,
    archetype: 'featherduster',
    size: 1.0,
    shape: { height: 1.0, finFlow: 1.2 },
    colors: {
      base: '#b78a5e',
      belly: '#e6d2b8',
      fin: '#f0e6d6',
      pattern: 'stripesH',
      patternColor: '#8a4a34',
      patternScale: 1.1,
      iridescence: 0.1
    },
    habitat: 'Warm shallow reefs and lagoons across the Indian and Pacific Oceans.',
    facts: [
      'It is really a worm that lives in a tube it builds itself, wearing a feathery crown on its head.',
      'The feathers are its fishing net, catching tiny bits of food that drift by in the water.',
      'If a shadow passes over, the whole crown vanishes into the tube in the blink of an eye.'
    ],
    care: 'Medium'
  },
  {
    id: 'chocolate_chip_starfish',
    common: 'Chocolate Chip Starfish',
    scientific: 'Protoreaster nodosus',
    water: 'salt',
    kind: 'invert',
    adultSizeCm: 15,
    bioload: 3,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.15,
    schooling: 'solo',
    diet: ['detritus', 'frozen', 'pellet'],
    edible: false,
    cleans: true,
    price: 20,
    archetype: 'star',
    size: 1.4,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#d9b06a',
      belly: '#e8cf9e',
      fin: '#d9b06a',
      pattern: 'spots',
      patternColor: '#4a3220',
      patternScale: 1.4,
      iridescence: 0.05
    },
    habitat: 'Sandy lagoons and seagrass beds of the warm Indo-Pacific ocean.',
    facts: [
      'The dark bumps on its back look exactly like chocolate chips on a cookie, but they are really armor spikes.',
      'To eat, it pushes its stomach out through its mouth and wraps it around its dinner.',
      'It walks on hundreds of tiny tube feet hidden under its arms, moving slower than a minute hand.'
    ],
    care: 'Medium'
  }
];
