// Saltwater species for the virtual aquarium. All suited to a 120g reef/FOWLR tank.
export const SALTWATER_SPECIES = [
  {
    id: 'ocellaris_clownfish',
    common: 'Ocellaris Clownfish',
    scientific: 'Amphiprion ocellaris',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 2,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['hostsAnemone'],
    zone: 'mid',
    speed: 0.8,
    schooling: 'pair',
    diet: ['pellet', 'frozen', 'flake'],
    price: 25,
    archetype: 'clown',
    size: 0.9,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#ff7a1a',
      belly: '#ff8c33',
      fin: '#1a1a1a',
      pattern: 'clownBands',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.15
    },
    habitat: 'Warm shallow reefs and lagoons of the Indo-Pacific, always near a host anemone.',
    facts: [
      'It rubs a slimy coat on the anemone so the stinging tentacles think it is a friend.',
      'Every clownfish is born a boy, and the biggest one in the group turns into the mother.',
      'It wiggles and dances to fan fresh water over its eggs to keep them healthy.'
    ],
    care: 'Easy'
  },
  {
    id: 'percula_clownfish',
    common: 'Percula Clownfish',
    scientific: 'Amphiprion percula',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 2,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['hostsAnemone'],
    zone: 'mid',
    speed: 0.8,
    schooling: 'pair',
    diet: ['pellet', 'frozen', 'flake'],
    price: 35,
    archetype: 'clown',
    size: 0.9,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#ff6a12',
      belly: '#ff7f26',
      fin: '#000000',
      pattern: 'clownBands',
      patternColor: '#fff7ea',
      patternScale: 1.0,
      iridescence: 0.15
    },
    habitat: 'Coral reefs of the western Pacific around Papua New Guinea and the Solomon Islands.',
    facts: [
      'It has thick black lines around its white bands, like it was drawn with a marker.',
      'A whole family can live in one anemone, and only the two biggest ones have babies.',
      'It almost never swims far from its anemone home its entire life.'
    ],
    care: 'Easy'
  },
  {
    id: 'tomato_clownfish',
    common: 'Tomato Clownfish',
    scientific: 'Amphiprion frenatus',
    water: 'salt',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 2,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['hostsAnemone'],
    zone: 'mid',
    speed: 0.85,
    schooling: 'pair',
    diet: ['pellet', 'frozen', 'flake'],
    price: 20,
    archetype: 'clown',
    size: 1.0,
    shape: { height: 1.15, finFlow: 1.0 },
    colors: {
      base: '#d62b1a',
      belly: '#e04434',
      fin: '#7a1710',
      pattern: 'clownBands',
      patternColor: '#ffffff',
      patternScale: 0.6,
      iridescence: 0.1
    },
    habitat: 'Sheltered lagoons and reef edges of the western Pacific and South China Sea.',
    facts: [
      'It only has one white stripe behind its head, unlike its three-striped cousins.',
      'The mother grows deep tomato-red while the father stays a brighter orange.',
      'It will bravely bump a diver who swims too close to its anemone.'
    ],
    care: 'Easy'
  },
  {
    id: 'maroon_clownfish',
    common: 'Maroon Clownfish',
    scientific: 'Premnas biaculeatus',
    water: 'salt',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 2,
    temperament: 'aggressive',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['hostsAnemone', 'soloOnly'],
    zone: 'mid',
    speed: 0.85,
    schooling: 'pair',
    diet: ['pellet', 'frozen', 'flake'],
    price: 30,
    archetype: 'clown',
    size: 1.1,
    shape: { height: 1.2, finFlow: 1.0 },
    colors: {
      base: '#7a1218',
      belly: '#961d24',
      fin: '#4d0b10',
      pattern: 'clownBands',
      patternColor: '#f0d67a',
      patternScale: 0.7,
      iridescence: 0.1
    },
    habitat: 'Coral reefs of the Indo-Pacific from India to the western Pacific.',
    facts: [
      'It is the biggest clownfish, and the mother can be twice the size of the father.',
      'It has little spikes on its cheeks that give it its other name, the spine-cheek clown.',
      'Its white stripes can turn golden as it grows older.'
    ],
    care: 'Medium'
  },
  {
    id: 'clarkii_clownfish',
    common: 'Clark\'s Clownfish',
    scientific: 'Amphiprion clarkii',
    water: 'salt',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 2,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['hostsAnemone'],
    zone: 'mid',
    speed: 0.9,
    schooling: 'pair',
    diet: ['pellet', 'frozen', 'flake'],
    price: 22,
    archetype: 'clown',
    size: 1.0,
    shape: { height: 1.15, finFlow: 1.0 },
    colors: {
      base: '#1c1c1c',
      belly: '#e8892a',
      fin: '#f2c24a',
      pattern: 'clownBands',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.12
    },
    habitat: 'A huge range of reefs across the Indian and Pacific Oceans from Africa to Japan.',
    facts: [
      'It is the least picky clownfish and will happily live in ten different kinds of anemone.',
      'Its bright yellow tail makes it easy to tell apart from other clownfish.',
      'It can live in cooler and warmer water than most of its clownfish cousins.'
    ],
    care: 'Easy'
  },
  {
    id: 'blue_tang',
    common: 'Blue Tang',
    scientific: 'Paracanthurus hepatus',
    water: 'salt',
    adultSizeCm: 30,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.1,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'pellet'],
    price: 60,
    archetype: 'tang',
    size: 1.1,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#1560c4',
      belly: '#2f74d0',
      fin: '#f4d21e',
      pattern: 'patches',
      patternColor: '#0a0a0a',
      patternScale: 1.1,
      iridescence: 0.35
    },
    habitat: 'Clear outer-reef waters of the Indo-Pacific where it darts among branching coral.',
    facts: [
      'When scared it lies flat and plays dead to trick hungry predators.',
      'It has a sharp blade near its tail that folds out like a pocket knife to defend itself.',
      'Baby blue tangs are bright yellow and turn blue as they grow up.'
    ],
    care: 'Medium'
  },
  {
    id: 'yellow_tang',
    common: 'Yellow Tang',
    scientific: 'Zebrasoma flavescens',
    water: 'salt',
    adultSizeCm: 20,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.0,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'flake'],
    price: 55,
    archetype: 'tang',
    size: 1.0,
    shape: { height: 1.35, finFlow: 1.1 },
    colors: {
      base: '#ffd60a',
      belly: '#ffdf33',
      fin: '#ffcf00',
      pattern: 'none',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Shallow reefs of Hawaii and the central Pacific where it grazes algae all day.',
    facts: [
      'At night its bright yellow fades and a white stripe appears so it can hide while sleeping.',
      'It has a white scalpel near its tail that it uses to warn other fish away.',
      'It helps the reef by nibbling algae off the coral like a tiny lawnmower.'
    ],
    care: 'Medium'
  },
  {
    id: 'purple_tang',
    common: 'Purple Tang',
    scientific: 'Zebrasoma xanthurum',
    water: 'salt',
    adultSizeCm: 25,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.05,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'flake'],
    price: 90,
    archetype: 'tang',
    size: 1.0,
    shape: { height: 1.35, finFlow: 1.1 },
    colors: {
      base: '#5a3fb0',
      belly: '#6d52c0',
      fin: '#f4c020',
      pattern: 'spots',
      patternColor: '#3a2680',
      patternScale: 0.7,
      iridescence: 0.3
    },
    habitat: 'Coral-rich reefs of the Red Sea and Arabian Sea.',
    facts: [
      'Its bright purple body ends in a sunny yellow tail like a paintbrush dipped in gold.',
      'It is one of the few reef fish that is a deep royal purple all over.',
      'It uses the sharp blade near its tail to guard its favorite feeding rock.'
    ],
    care: 'Medium'
  },
  {
    id: 'powder_blue_tang',
    common: 'Powder Blue Tang',
    scientific: 'Acanthurus leucosternon',
    water: 'salt',
    adultSizeCm: 23,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.15,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'flake'],
    price: 75,
    archetype: 'tang',
    size: 1.05,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#7db6e8',
      belly: '#9cc8ef',
      fin: '#f4d21e',
      pattern: 'patches',
      patternColor: '#1a1a1a',
      patternScale: 1.0,
      iridescence: 0.35
    },
    habitat: 'Wave-washed outer reefs of the Indian Ocean around Sri Lanka and the Maldives.',
    facts: [
      'It has a soft powder-blue body with a black face like it is wearing a mask.',
      'In the wild it grazes in big grazing groups that sweep across the reef.',
      'Its bright yellow fins flash as a warning that it carries a sharp tail blade.'
    ],
    care: 'Hard'
  },
  {
    id: 'kole_tang',
    common: 'Kole Tang',
    scientific: 'Ctenochaetus strigosus',
    water: 'salt',
    adultSizeCm: 18,
    bioload: 4,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.0,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'flake'],
    price: 45,
    archetype: 'tang',
    size: 0.95,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#5a4632',
      belly: '#6e5940',
      fin: '#4a3826',
      pattern: 'lateralStripe',
      patternColor: '#c9a24a',
      patternScale: 1.4,
      iridescence: 0.25
    },
    habitat: 'Rocky reefs and rubble slopes around the Hawaiian Islands.',
    facts: [
      'It has a golden ring around its eye that makes it look like it is wearing glasses.',
      'Its mouth has tiny comb-like teeth to scrape slimy film off the rocks.',
      'It is one of the calmest tangs and rarely bothers its tankmates.'
    ],
    care: 'Medium'
  },
  {
    id: 'scopas_tang',
    common: 'Scopas Tang',
    scientific: 'Zebrasoma scopas',
    water: 'salt',
    adultSizeCm: 20,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.0,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'flake'],
    price: 40,
    archetype: 'tang',
    size: 1.0,
    shape: { height: 1.35, finFlow: 1.1 },
    colors: {
      base: '#6b5a3e',
      belly: '#8a7550',
      fin: '#3a3226',
      pattern: 'spots',
      patternColor: '#c8b26a',
      patternScale: 0.6,
      iridescence: 0.25
    },
    habitat: 'Coral and rubble reefs across the Indo-Pacific from Africa to Hawaii.',
    facts: [
      'It fades from dark brown at the tail to a lighter shade near its face.',
      'When it grows up its dorsal and belly fins stretch out into tall sails.',
      'Tiny sparkly dots cover its head like a sprinkle of gold dust.'
    ],
    care: 'Medium'
  },
  {
    id: 'tomini_tang',
    common: 'Tomini Tang',
    scientific: 'Ctenochaetus tominiensis',
    water: 'salt',
    adultSizeCm: 15,
    bioload: 4,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.0,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'flake'],
    price: 50,
    archetype: 'tang',
    size: 0.9,
    shape: { height: 1.3, finFlow: 1.0 },
    colors: {
      base: '#4a3d30',
      belly: '#6a5844',
      fin: '#e8b024',
      pattern: 'gradientTail',
      patternColor: '#3a2f24',
      patternScale: 1.0,
      iridescence: 0.25
    },
    habitat: 'Reef slopes of the western Pacific around Indonesia and the Philippines.',
    facts: [
      'Its dorsal and belly fins glow bright orange along the edges.',
      'It stays small for a tang, so it fits in tanks its bigger cousins would outgrow.',
      'It picks tiny food off the rocks with its comb-shaped teeth all day long.'
    ],
    care: 'Medium'
  },
  {
    id: 'sailfin_tang',
    common: 'Sailfin Tang',
    scientific: 'Zebrasoma velifer',
    water: 'salt',
    adultSizeCm: 38,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.05,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'flake'],
    price: 65,
    archetype: 'tang',
    size: 1.15,
    shape: { height: 1.5, finFlow: 1.2 },
    colors: {
      base: '#c8a24a',
      belly: '#e0c070',
      fin: '#8a6a30',
      pattern: 'stripesV',
      patternColor: '#5a4726',
      patternScale: 1.1,
      iridescence: 0.25
    },
    habitat: 'Shallow lagoons and reef flats of the Indo-Pacific.',
    facts: [
      'When it spreads its huge fins it looks almost as tall as it is long.',
      'It puffs up its giant sail fins to look bigger and scare off rivals.',
      'Wide brown and cream stripes help it blend into sun-dappled coral.'
    ],
    care: 'Medium'
  },
  {
    id: 'foxface_rabbitfish',
    common: 'Foxface Rabbitfish',
    scientific: 'Siganus vulpinus',
    water: 'salt',
    adultSizeCm: 24,
    bioload: 8,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.95,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'flake'],
    price: 45,
    archetype: 'tang',
    size: 1.1,
    shape: { height: 1.35, finFlow: 1.0 },
    colors: {
      base: '#f4c81e',
      belly: '#ffe066',
      fin: '#f0c020',
      pattern: 'patches',
      patternColor: '#f5f5f0',
      patternScale: 1.2,
      iridescence: 0.15
    },
    habitat: 'Lagoons and sheltered reefs of the western Pacific where it hides in coral at night.',
    facts: [
      'Its face has a black-and-white mask like a fox, which gives it its name.',
      'Its spines carry a mild venom, so it only needs to point them to stay safe.',
      'When it sleeps it turns a mottled brown to hide, then goes bright yellow by day.'
    ],
    care: 'Easy'
  },
  {
    id: 'royal_gramma',
    common: 'Royal Gramma',
    scientific: 'Gramma loreto',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.8,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 25,
    archetype: 'cichlid',
    size: 0.7,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#8a3fd0',
      belly: '#f4d21e',
      fin: '#f4d21e',
      pattern: 'gradientTail',
      patternColor: '#a95fe0',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Shady reef caves and ledges of the Caribbean Sea.',
    facts: [
      'Its front half is purple and its back half is yellow, split right down the middle.',
      'It likes to swim upside down under ledges, following the roof of its cave.',
      'It carries its eggs in a little nest of algae and guards them until they hatch.'
    ],
    care: 'Easy'
  },
  {
    id: 'blackcap_basslet',
    common: 'Blackcap Basslet',
    scientific: 'Gramma melacara',
    water: 'salt',
    adultSizeCm: 10,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.85,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 60,
    archetype: 'cichlid',
    size: 0.75,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#c14fb0',
      belly: '#d76fc4',
      fin: '#b03fa0',
      pattern: 'patches',
      patternColor: '#1a1a1a',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Deep reef walls and caves of the Caribbean around the Bahamas.',
    facts: [
      'It has a bright magenta body with a black cap over its head like a little hat.',
      'It lives on steep reef cliffs and darts back into caves when startled.',
      'Like the royal gramma, it loves to hover upside down under rocky ledges.'
    ],
    care: 'Easy'
  },
  {
    id: 'royal_dottyback',
    common: 'Royal Dottyback',
    scientific: 'Pseudochromis paccagnellae',
    water: 'salt',
    adultSizeCm: 7,
    bioload: 2,
    minSchool: 1,
    temperament: 'aggressive',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.0,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 22,
    archetype: 'clown',
    size: 0.65,
    shape: { height: 0.9, finFlow: 1.0 },
    colors: {
      base: '#8a2fc0',
      belly: '#f4c81e',
      fin: '#f4c81e',
      pattern: 'patches',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Rubble and coral crevices of the western Pacific around Indonesia.',
    facts: [
      'It looks like a royal gramma but has a thin white line between its two colors.',
      'It is tiny but very brave and will chase fish many times its size.',
      'It hides in a favorite hole and pokes its head out to watch for food.'
    ],
    care: 'Easy'
  },
  {
    id: 'orchid_dottyback',
    common: 'Orchid Dottyback',
    scientific: 'Pseudochromis fridmani',
    water: 'salt',
    adultSizeCm: 7,
    bioload: 2,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 30,
    archetype: 'clown',
    size: 0.65,
    shape: { height: 0.9, finFlow: 1.0 },
    colors: {
      base: '#a24fd8',
      belly: '#b56fe4',
      fin: '#9040cc',
      pattern: 'lateralStripe',
      patternColor: '#6a2fa0',
      patternScale: 2.0,
      iridescence: 0.35
    },
    habitat: 'Steep coral drop-offs and caves of the Red Sea.',
    facts: [
      'It is a glowing purple all over with a thin dark stripe through its eye.',
      'It sometimes cleans other fish by nibbling pesky bugs off their skin.',
      'It darts in and out of cracks in the reef, rarely swimming in the open.'
    ],
    care: 'Easy'
  },
  {
    id: 'mandarin_dragonet',
    common: 'Mandarin Dragonet',
    scientific: 'Synchiropus splendidus',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['expertDiet'],
    zone: 'bottom',
    speed: 0.5,
    schooling: 'solo',
    diet: ['frozen'],
    price: 35,
    archetype: 'goby',
    size: 0.7,
    shape: { height: 0.9, finFlow: 1.0 },
    colors: {
      base: '#1f8a5a',
      belly: '#f28a1a',
      fin: '#2f6fc0',
      pattern: 'stripesH',
      patternColor: '#ff6a1a',
      patternScale: 1.6,
      iridescence: 0.5
    },
    habitat: 'Sheltered lagoons and inshore reefs of the western Pacific where it hops over rubble.',
    facts: [
      'It is covered in swirly orange and blue lines like a fancy painted rug.',
      'Instead of scales it wears a slimy coat that smells bad so predators leave it alone.',
      'It hunts all day, picking hundreds of tiny bugs off the live rock one by one.'
    ],
    care: 'Hard'
  },
  {
    id: 'spotted_mandarin',
    common: 'Spotted Mandarin',
    scientific: 'Synchiropus picturatus',
    water: 'salt',
    adultSizeCm: 7,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['expertDiet'],
    zone: 'bottom',
    speed: 0.5,
    schooling: 'solo',
    diet: ['frozen'],
    price: 35,
    archetype: 'goby',
    size: 0.7,
    shape: { height: 0.9, finFlow: 1.0 },
    colors: {
      base: '#2f7a4a',
      belly: '#3a8a55',
      fin: '#2f6fc0',
      pattern: 'eyespot',
      patternColor: '#0a0a0a',
      patternScale: 1.2,
      iridescence: 0.5
    },
    habitat: 'Coral rubble and reef flats of the western Pacific around Indonesia.',
    facts: [
      'It wears bright green with black-ringed spots that look like little targets.',
      'It slowly hovers over the sand looking for tiny bugs to snap up.',
      'Its beautiful colors are actually a warning that it tastes terrible.'
    ],
    care: 'Hard'
  },
  {
    id: 'green_chromis',
    common: 'Green Chromis',
    scientific: 'Chromis viridis',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.2,
    schooling: 'tight',
    diet: ['frozen', 'pellet', 'flake'],
    price: 12,
    archetype: 'torpedo',
    size: 0.7,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#4fd0b0',
      belly: '#a8f0e0',
      fin: '#5fd8bc',
      pattern: 'none',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.7
    },
    habitat: 'Branching coral heads of the Indo-Pacific where whole schools shelter together.',
    facts: [
      'A big group shimmers green and blue as it turns in the sunlight.',
      'When danger comes the whole school dives into the coral branches at once.',
      'The father guards the eggs he laid on the coral and fans them with his fins.'
    ],
    care: 'Easy'
  },
  {
    id: 'blue_reef_chromis',
    common: 'Blue Reef Chromis',
    scientific: 'Chromis cyanea',
    water: 'salt',
    adultSizeCm: 12,
    bioload: 2,
    minSchool: 6,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.2,
    schooling: 'tight',
    diet: ['frozen', 'pellet', 'flake'],
    price: 18,
    archetype: 'torpedo',
    size: 0.75,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#1a6fd8',
      belly: '#3a8ce8',
      fin: '#0a0a1a',
      pattern: 'none',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.7
    },
    habitat: 'Outer reef edges of the Caribbean where schools hover in the current.',
    facts: [
      'Its body is an electric blue that seems to glow against the reef.',
      'It swims out into the open water to catch drifting food, then darts back home.',
      'A whole school faces into the current together, waiting for food to float by.'
    ],
    care: 'Easy'
  },
  {
    id: 'lyretail_anthias',
    common: 'Lyretail Anthias',
    scientific: 'Pseudanthias squamipinnis',
    water: 'salt',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 4,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.15,
    schooling: 'loose',
    diet: ['frozen', 'pellet', 'flake'],
    price: 30,
    archetype: 'cichlid',
    size: 0.8,
    shape: { height: 1.1, finFlow: 1.2 },
    colors: {
      base: '#ff8a4a',
      belly: '#ffb07a',
      fin: '#ff6a2a',
      pattern: 'gradientTail',
      patternColor: '#e04a80',
      patternScale: 1.0,
      iridescence: 0.4
    },
    habitat: 'Current-swept reef slopes of the Indo-Pacific and Red Sea.',
    facts: [
      'It lives in huge clouds of hundreds of fish that hover above the coral.',
      'If the one male disappears, the biggest female turns into a new male to lead.',
      'The males are pinky-purple and the females are bright orange.'
    ],
    care: 'Medium'
  },
  {
    id: 'chalk_bass',
    common: 'Chalk Bass',
    scientific: 'Serranus tortugarum',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.9,
    schooling: 'loose',
    diet: ['frozen', 'pellet', 'flake'],
    price: 20,
    archetype: 'cichlid',
    size: 0.65,
    shape: { height: 0.9, finFlow: 1.0 },
    colors: {
      base: '#c86a5a',
      belly: '#d88a7a',
      fin: '#8a9ac8',
      pattern: 'lateralStripe',
      patternColor: '#5a7ac0',
      patternScale: 1.2,
      iridescence: 0.35
    },
    habitat: 'Rubble and reef bases of the Caribbean and Gulf of Mexico.',
    facts: [
      'Its peachy body glows with sky-blue lines along the top.',
      'It is one of the few reef fish that is happy living in a little group.',
      'It hovers near the sand and dashes down to grab tiny food.'
    ],
    care: 'Easy'
  },
  {
    id: 'firefish',
    common: 'Firefish',
    scientific: 'Nemateleotris magnifica',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'bottom',
    speed: 0.9,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 20,
    archetype: 'goby',
    size: 0.7,
    shape: { height: 0.8, finFlow: 1.1 },
    colors: {
      base: '#f4f0e8',
      belly: '#fbf8f2',
      fin: '#e83a1a',
      pattern: 'gradientTail',
      patternColor: '#ff5a2a',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Sandy reef edges of the Indo-Pacific where it hovers above its burrow.',
    facts: [
      'Its tail end is fiery red, fading to white near its face like a candle flame.',
      'It flicks a tall spiky fin up and down on its back like a little flag.',
      'At the first sign of danger it dives head-first into a hole in the sand.'
    ],
    care: 'Easy'
  },
  {
    id: 'purple_firefish',
    common: 'Purple Firefish',
    scientific: 'Nemateleotris decora',
    water: 'salt',
    adultSizeCm: 9,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'bottom',
    speed: 0.9,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 28,
    archetype: 'goby',
    size: 0.7,
    shape: { height: 0.8, finFlow: 1.1 },
    colors: {
      base: '#e8e4dc',
      belly: '#f2eee6',
      fin: '#7a2fc0',
      pattern: 'gradientTail',
      patternColor: '#9040d8',
      patternScale: 1.0,
      iridescence: 0.25
    },
    habitat: 'Deeper sandy reef slopes of the Indo-Pacific.',
    facts: [
      'It has a purple face and bright purple fins with a golden head.',
      'It hovers just above the sand, ready to zip into its burrow if scared.',
      'It often shares its sandy home with a partner of the same kind.'
    ],
    care: 'Easy'
  },
  {
    id: 'yellow_watchman_goby',
    common: 'Yellow Watchman Goby',
    scientific: 'Cryptocentrus cinctus',
    water: 'salt',
    adultSizeCm: 9,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.7,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 22,
    archetype: 'goby',
    size: 0.8,
    shape: { height: 0.9, finFlow: 1.0 },
    colors: {
      base: '#f4c81e',
      belly: '#ffd84a',
      fin: '#e8b81a',
      pattern: 'spots',
      patternColor: '#5aa0e0',
      patternScale: 0.8,
      iridescence: 0.3
    },
    habitat: 'Sandy reef flats of the western Pacific where it shares a burrow with a shrimp.',
    facts: [
      'It teams up with a nearly blind shrimp that digs a burrow they both live in.',
      'The goby keeps watch and flicks its tail to warn the shrimp when danger comes.',
      'It has bright blue speckles scattered across its sunny yellow body.'
    ],
    care: 'Easy'
  },
  {
    id: 'diamond_goby',
    common: 'Diamond Watchman Goby',
    scientific: 'Valenciennea puellaris',
    water: 'salt',
    adultSizeCm: 14,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.75,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 20,
    archetype: 'goby',
    size: 0.85,
    shape: { height: 0.85, finFlow: 1.0 },
    colors: {
      base: '#f4efe4',
      belly: '#fbf8f0',
      fin: '#e8dcc4',
      pattern: 'spots',
      patternColor: '#f0a83a',
      patternScale: 1.0,
      iridescence: 0.25
    },
    habitat: 'Sandy lagoon bottoms of the Indo-Pacific where it sifts the sand for food.',
    facts: [
      'It scoops up mouthfuls of sand, eats the tiny critters, and spits the sand back out.',
      'Its pearly white body is dotted with sparkly orange diamonds.',
      'It keeps the sand clean and bright by sifting it over and over all day.'
    ],
    care: 'Easy'
  },
  {
    id: 'clown_goby',
    common: 'Yellow Clown Goby',
    scientific: 'Gobiodon okinawae',
    water: 'salt',
    adultSizeCm: 4,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.6,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 15,
    archetype: 'goby',
    size: 0.5,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#ffcf1a',
      belly: '#ffdb4a',
      fin: '#f0bf10',
      pattern: 'none',
      patternColor: '#ffffff',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Branching coral heads of the western Pacific where it perches on the branches.',
    facts: [
      'It is tiny and bright yellow and loves to perch inside coral branches.',
      'It has no swim bladder, so it rests on coral instead of floating in the water.',
      'It lays its eggs right on the coral and both parents guard them.'
    ],
    care: 'Easy'
  },
  {
    id: 'neon_goby',
    common: 'Neon Goby',
    scientific: 'Elacatinus oceanops',
    water: 'salt',
    adultSizeCm: 5,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.7,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 15,
    archetype: 'goby',
    size: 0.5,
    shape: { height: 0.8, finFlow: 1.0 },
    colors: {
      base: '#1a1a22',
      belly: '#2a2a33',
      fin: '#1a1a22',
      pattern: 'lateralStripe',
      patternColor: '#2fd0ff',
      patternScale: 1.4,
      iridescence: 0.6
    },
    habitat: 'Coral reefs of the Caribbean where it sets up cleaning stations.',
    facts: [
      'It runs a cleaning station where big fish line up to have their teeth cleaned.',
      'It swims right inside a big fish\'s mouth to eat pests and never gets swallowed.',
      'A glowing blue stripe runs the whole length of its little black body.'
    ],
    care: 'Easy'
  },
  {
    id: 'lawnmower_blenny',
    common: 'Lawnmower Blenny',
    scientific: 'Salarias fasciatus',
    water: 'salt',
    adultSizeCm: 13,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.7,
    schooling: 'solo',
    diet: ['algae', 'frozen'],
    price: 18,
    archetype: 'goby',
    size: 0.85,
    shape: { height: 0.85, finFlow: 1.0 },
    colors: {
      base: '#8a7a5a',
      belly: '#a89676',
      fin: '#6e5f45',
      pattern: 'patches',
      patternColor: '#4a4030',
      patternScale: 1.2,
      iridescence: 0.15
    },
    habitat: 'Algae-covered reef flats of the Indo-Pacific where it grazes on the rocks.',
    facts: [
      'It scrapes green algae off the rocks all day like a tiny lawnmower.',
      'It can change its mottled colors to match the rock it is sitting on.',
      'Its big frog-like eyes swivel around to watch for food and danger.'
    ],
    care: 'Easy'
  },
  {
    id: 'bicolor_blenny',
    common: 'Bicolor Blenny',
    scientific: 'Ecsenius bicolor',
    water: 'salt',
    adultSizeCm: 10,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.75,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'pellet'],
    price: 15,
    archetype: 'goby',
    size: 0.75,
    shape: { height: 0.8, finFlow: 1.0 },
    colors: {
      base: '#3a5aa8',
      belly: '#4a6ab8',
      fin: '#f08a2a',
      pattern: 'gradientTail',
      patternColor: '#ff9a3a',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Coral and rubble reefs of the Indo-Pacific where it hides in small holes.',
    facts: [
      'Its front half is dark blue and its back half is bright orange.',
      'It backs into an empty snail shell or hole and peeks out with its big eyes.',
      'It hops from rock to rock instead of swimming smoothly like other fish.'
    ],
    care: 'Easy'
  },
  {
    id: 'midas_blenny',
    common: 'Midas Blenny',
    scientific: 'Ecsenius midas',
    water: 'salt',
    adultSizeCm: 13,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 25,
    archetype: 'goby',
    size: 0.8,
    shape: { height: 0.85, finFlow: 1.1 },
    colors: {
      base: '#f0a81a',
      belly: '#ffc24a',
      fin: '#e89810',
      pattern: 'gradientTail',
      patternColor: '#c87a10',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Reef slopes of the Indian Ocean and Red Sea where it darts among the rocks.',
    facts: [
      'It is golden all over, which is why it is named after King Midas.',
      'It has an eel-like wiggly swim and a long flowing tail.',
      'It sneaks into schools of anthias and pretends to be one of them.'
    ],
    care: 'Easy'
  },
  {
    id: 'tailspot_blenny',
    common: 'Tailspot Blenny',
    scientific: 'Ecsenius stigmatura',
    water: 'salt',
    adultSizeCm: 6,
    bioload: 1,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.7,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'pellet'],
    price: 20,
    archetype: 'goby',
    size: 0.6,
    shape: { height: 0.8, finFlow: 1.0 },
    colors: {
      base: '#6a8a7a',
      belly: '#8aa898',
      fin: '#f0c02a',
      pattern: 'eyespot',
      patternColor: '#1a1a1a',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Shallow coral reefs of the western Pacific around Indonesia.',
    facts: [
      'It has a black spot near its tail that looks like a fake eye to fool predators.',
      'A bright yellow-orange mark curves under each of its eyes.',
      'It perches on the rocks and grazes on tiny bits of algae.'
    ],
    care: 'Easy'
  },
  {
    id: 'six_line_wrasse',
    common: 'Six Line Wrasse',
    scientific: 'Pseudocheilinus hexataenia',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.2,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 18,
    archetype: 'torpedo',
    size: 0.65,
    shape: { height: 0.9, finFlow: 1.0 },
    colors: {
      base: '#7a3fc0',
      belly: '#e86a1a',
      fin: '#4fd0a0',
      pattern: 'stripesH',
      patternColor: '#2fb0ff',
      patternScale: 1.4,
      iridescence: 0.4
    },
    habitat: 'Coral thickets of the Indo-Pacific where it weaves through the branches.',
    facts: [
      'Six neon blue lines run along its purple-orange body from nose to tail.',
      'It has a spot near its tail that looks like an eye to confuse attackers.',
      'It zips through the coral all day hunting tiny bugs and pest snails.'
    ],
    care: 'Easy'
  },
  {
    id: 'melanurus_wrasse',
    common: 'Melanurus Wrasse',
    scientific: 'Halichoeres melanurus',
    water: 'salt',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'mid',
    speed: 1.3,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 25,
    archetype: 'torpedo',
    size: 0.8,
    shape: { height: 0.85, finFlow: 1.0 },
    colors: {
      base: '#2f9a6a',
      belly: '#3aae7a',
      fin: '#e85a8a',
      pattern: 'stripesH',
      patternColor: '#e85a8a',
      patternScale: 1.2,
      iridescence: 0.45
    },
    habitat: 'Rubble and coral reefs of the western Pacific where it hunts along the bottom.',
    facts: [
      'Its green body is covered with squiggly pink lines like a maze.',
      'At night it burrows under the sand to sleep, hidden from predators.',
      'It hunts pest bugs and worms that bother corals, so reef keepers love it.'
    ],
    care: 'Easy'
  },
  {
    id: 'yellow_coris_wrasse',
    common: 'Yellow Coris Wrasse',
    scientific: 'Halichoeres chrysus',
    water: 'salt',
    adultSizeCm: 12,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['jumper'],
    zone: 'mid',
    speed: 1.3,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 22,
    archetype: 'torpedo',
    size: 0.75,
    shape: { height: 0.85, finFlow: 1.0 },
    colors: {
      base: '#ffcf14',
      belly: '#ffdb44',
      fin: '#f0bf0a',
      pattern: 'eyespot',
      patternColor: '#1a1a1a',
      patternScale: 1.0,
      iridescence: 0.4
    },
    habitat: 'Sandy patches near reefs of the Indo-Pacific where it dives into the sand at night.',
    facts: [
      'It is a bright sunny yellow with a black false eye on its back fin.',
      'When it feels scared or wants to sleep, it dives right into the sand.',
      'It swims by rowing with its fins, giving it a bouncy hopping motion.'
    ],
    care: 'Easy'
  },
  {
    id: 'cleaner_wrasse',
    common: 'Bluestreak Cleaner Wrasse',
    scientific: 'Labroides dimidiatus',
    water: 'salt',
    adultSizeCm: 11,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['expertDiet'],
    zone: 'mid',
    speed: 1.1,
    schooling: 'solo',
    diet: ['frozen'],
    price: 20,
    archetype: 'torpedo',
    size: 0.7,
    shape: { height: 0.8, finFlow: 1.0 },
    colors: {
      base: '#cfe0ea',
      belly: '#e4eef4',
      fin: '#1a3a8a',
      pattern: 'lateralStripe',
      patternColor: '#0a1a5a',
      patternScale: 1.6,
      iridescence: 0.4
    },
    habitat: 'Coral reefs of the Indo-Pacific where it runs a cleaning station all day.',
    facts: [
      'Big fish visit it to have dead skin and pests picked off their bodies.',
      'It does a little bobbing dance to tell fish that its cleaning station is open.',
      'A bold black stripe runs down its body so customers can spot it easily.'
    ],
    care: 'Hard'
  },
  {
    id: 'banggai_cardinalfish',
    common: 'Banggai Cardinalfish',
    scientific: 'Pterapogon kauderni',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.7,
    schooling: 'loose',
    diet: ['frozen', 'pellet'],
    price: 25,
    archetype: 'clown',
    size: 0.8,
    shape: { height: 1.3, finFlow: 1.3 },
    colors: {
      base: '#c8ccd4',
      belly: '#dde0e6',
      fin: '#1a1a22',
      pattern: 'stripesV',
      patternColor: '#0a0a12',
      patternScale: 1.0,
      iridescence: 0.35
    },
    habitat: 'Shallow seagrass and rubble around the Banggai Islands of Indonesia only.',
    facts: [
      'The father keeps the eggs and babies safe inside his mouth until they can swim.',
      'Its silver body has bold black stripes and a spray of white polka dots.',
      'Baby Banggais hide among the long spines of sea urchins to stay safe.'
    ],
    care: 'Easy'
  },
  {
    id: 'pajama_cardinalfish',
    common: 'Pajama Cardinalfish',
    scientific: 'Sphaeramia nematoptera',
    water: 'salt',
    adultSizeCm: 9,
    bioload: 2,
    minSchool: 3,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['nocturnal'],
    zone: 'mid',
    speed: 0.7,
    schooling: 'loose',
    diet: ['frozen', 'pellet'],
    price: 20,
    archetype: 'clown',
    size: 0.8,
    shape: { height: 1.25, finFlow: 1.1 },
    colors: {
      base: '#f4e04a',
      belly: '#e86a5a',
      fin: '#f0d84a',
      pattern: 'spots',
      patternColor: '#c02a4a',
      patternScale: 0.9,
      iridescence: 0.3
    },
    habitat: 'Sheltered lagoons of the western Pacific where it rests among coral by day.',
    facts: [
      'It looks like it is wearing mismatched pajamas with a yellow face and spotty back.',
      'It rests quietly in the coral by day and comes out to hunt at night.',
      'The father carries the eggs in his mouth and does not eat until they hatch.'
    ],
    care: 'Easy'
  },
  {
    id: 'flame_angelfish',
    common: 'Flame Angelfish',
    scientific: 'Centropyge loriculus',
    water: 'salt',
    adultSizeCm: 10,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 0.95,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'pellet'],
    price: 55,
    archetype: 'tang',
    size: 0.8,
    shape: { height: 1.25, finFlow: 1.0 },
    colors: {
      base: '#f43a12',
      belly: '#ff6a2a',
      fin: '#2a2f7a',
      pattern: 'stripesV',
      patternColor: '#1a1a1a',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Coral-rich outer reefs of the central Pacific where it darts between hideouts.',
    facts: [
      'Its body glows fiery red-orange with black tiger stripes down the sides.',
      'It is shy and always stays close to a hole it can dash into.',
      'The tips of its back and belly fins shine electric blue.'
    ],
    care: 'Medium'
  },
  {
    id: 'coral_beauty',
    common: 'Coral Beauty Angelfish',
    scientific: 'Centropyge bispinosa',
    water: 'salt',
    adultSizeCm: 10,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 0.9,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'pellet'],
    price: 40,
    archetype: 'tang',
    size: 0.8,
    shape: { height: 1.25, finFlow: 1.0 },
    colors: {
      base: '#7a2f8a',
      belly: '#e86a2a',
      fin: '#5a2470',
      pattern: 'stripesV',
      patternColor: '#4a1a5a',
      patternScale: 1.2,
      iridescence: 0.35
    },
    habitat: 'Coral slopes and caves of the Indo-Pacific where it grazes on algae.',
    facts: [
      'It has a deep purple body with a glowing orange middle full of dark stripes.',
      'It is one of the toughest and easiest of all the dwarf angelfish.',
      'It nibbles algae from the rocks and hides in caves when it feels shy.'
    ],
    care: 'Easy'
  },
  {
    id: 'lemonpeel_angelfish',
    common: 'Lemonpeel Angelfish',
    scientific: 'Centropyge flavissima',
    water: 'salt',
    adultSizeCm: 14,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 0.9,
    schooling: 'solo',
    diet: ['algae', 'frozen', 'pellet'],
    price: 45,
    archetype: 'tang',
    size: 0.85,
    shape: { height: 1.25, finFlow: 1.0 },
    colors: {
      base: '#ffcf10',
      belly: '#ffdb40',
      fin: '#ffcf10',
      pattern: 'none',
      patternColor: '#3a6ac0',
      patternScale: 1.0,
      iridescence: 0.3
    },
    habitat: 'Shallow lagoons and reef flats of the central and western Pacific.',
    facts: [
      'It is bright lemon yellow with a sky-blue ring around each eye.',
      'Baby lemonpeels have a black spot with a blue ring, like a fake eye.',
      'It spends its day grazing algae off the rocks and coral.'
    ],
    care: 'Medium'
  },
  {
    id: 'copperband_butterflyfish',
    common: 'Copperband Butterflyfish',
    scientific: 'Chelmon rostratus',
    water: 'salt',
    adultSizeCm: 20,
    bioload: 8,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['expertDiet'],
    zone: 'mid',
    speed: 0.85,
    schooling: 'solo',
    diet: ['frozen'],
    price: 45,
    archetype: 'tang',
    size: 1.0,
    shape: { height: 1.4, finFlow: 1.0 },
    colors: {
      base: '#f7f2e8',
      belly: '#fbf8f0',
      fin: '#f0a81a',
      pattern: 'stripesV',
      patternColor: '#f0a81a',
      patternScale: 1.1,
      iridescence: 0.2
    },
    habitat: 'Reef edges and estuaries of the western Pacific where it probes cracks for food.',
    facts: [
      'It has a long thin snout like tweezers to pull food out of tiny cracks.',
      'A black eyespot near its tail tricks predators into biting the wrong end.',
      'Its silvery body is banded with coppery orange stripes like a tiger.'
    ],
    care: 'Hard'
  },
  {
    id: 'raccoon_butterflyfish',
    common: 'Raccoon Butterflyfish',
    scientific: 'Chaetodon lunula',
    water: 'salt',
    adultSizeCm: 20,
    bioload: 8,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.9,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'algae'],
    price: 40,
    archetype: 'tang',
    size: 1.0,
    shape: { height: 1.4, finFlow: 1.0 },
    colors: {
      base: '#f0a828',
      belly: '#f8c860',
      fin: '#e89818',
      pattern: 'patches',
      patternColor: '#1a1a1a',
      patternScale: 1.1,
      iridescence: 0.2
    },
    habitat: 'Reef flats and lagoons of the Indo-Pacific where it forages at dusk.',
    facts: [
      'It has a black mask across its eyes like a raccoon\'s face.',
      'It rests quietly by day and comes out to hunt as the sun goes down.',
      'The dark bar over its eye hides where it is really looking.'
    ],
    care: 'Medium'
  },
  {
    id: 'longnose_hawkfish',
    common: 'Longnose Hawkfish',
    scientific: 'Oxycirrhites typus',
    water: 'salt',
    adultSizeCm: 13,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.8,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 45,
    archetype: 'goby',
    size: 0.85,
    shape: { height: 0.85, finFlow: 1.0 },
    colors: {
      base: '#f4efe6',
      belly: '#fbf8f2',
      fin: '#e0442a',
      pattern: 'patches',
      patternColor: '#e0442a',
      patternScale: 1.1,
      iridescence: 0.2
    },
    habitat: 'Deep reefs of the Indo-Pacific where it perches on sea fans and black coral.',
    facts: [
      'Its body is covered in a red-and-white checkerboard pattern.',
      'It has no swim bladder, so it props itself on coral like a bird on a branch.',
      'It waits perfectly still, then pounces on tiny shrimp that swim past.'
    ],
    care: 'Easy'
  },
  {
    id: 'flame_hawkfish',
    common: 'Flame Hawkfish',
    scientific: 'Neocirrhites armatus',
    water: 'salt',
    adultSizeCm: 9,
    bioload: 2,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.85,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 55,
    archetype: 'goby',
    size: 0.75,
    shape: { height: 0.9, finFlow: 1.0 },
    colors: {
      base: '#e01a12',
      belly: '#f03a2a',
      fin: '#c01008',
      pattern: 'lateralStripe',
      patternColor: '#1a1a1a',
      patternScale: 1.4,
      iridescence: 0.25
    },
    habitat: 'Wave-swept coral heads of the Pacific where it darts among the branches.',
    facts: [
      'It is a bright fire-red with a black stripe running along its back.',
      'It perches on coral with its fan-shaped fins and hops from spot to spot.',
      'It has little feathery tufts on the tips of its back fin spines.'
    ],
    care: 'Easy'
  },
  {
    id: 'volitans_lionfish',
    common: 'Volitans Lionfish',
    scientific: 'Pterois volitans',
    water: 'salt',
    adultSizeCm: 35,
    bioload: 14,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: true,
    tags: ['nocturnal'],
    zone: 'mid',
    speed: 0.6,
    schooling: 'solo',
    diet: ['frozen'],
    price: 50,
    archetype: 'lionfish',
    size: 1.2,
    shape: { height: 1.2, finFlow: 1.5 },
    colors: {
      base: '#a83a2a',
      belly: '#e8dcc8',
      fin: '#c85a3a',
      pattern: 'stripesV',
      patternColor: '#e8e0d0',
      patternScale: 1.1,
      iridescence: 0.15
    },
    habitat: 'Reefs and lagoons of the Indo-Pacific where it hunts small fish at dusk.',
    facts: [
      'It has long fanned-out fins that it uses to corner small fish before gulping them.',
      'Its spiky spines carry a sting, so it wears bold stripes as a warning.',
      'It can swallow a fish almost as long as its own body in one big gulp.'
    ],
    care: 'Medium'
  },
  {
    id: 'dwarf_fuzzy_lionfish',
    common: 'Dwarf Fuzzy Lionfish',
    scientific: 'Dendrochirus brachypterus',
    water: 'salt',
    adultSizeCm: 17,
    bioload: 8,
    minSchool: 1,
    temperament: 'semi',
    predator: true,
    finNipper: false,
    longFins: true,
    tags: ['nocturnal'],
    zone: 'bottom',
    speed: 0.55,
    schooling: 'solo',
    diet: ['frozen'],
    price: 40,
    archetype: 'lionfish',
    size: 0.9,
    shape: { height: 1.15, finFlow: 1.3 },
    colors: {
      base: '#b06a3a',
      belly: '#e0c8a8',
      fin: '#c88a5a',
      pattern: 'stripesV',
      patternColor: '#7a4a2a',
      patternScale: 1.0,
      iridescence: 0.1
    },
    habitat: 'Weedy and rubble bottoms of the western Pacific where it stalks tiny prey.',
    facts: [
      'It is a small lionfish with fan-like fins covered in a fuzzy feathery look.',
      'It can change its shade to blend in with the rocks and seaweed.',
      'It slowly herds shrimp into a corner with its wide fins before it strikes.'
    ],
    care: 'Medium'
  },
  {
    id: 'valentini_puffer',
    common: 'Valentini Puffer',
    scientific: 'Canthigaster valentini',
    water: 'salt',
    adultSizeCm: 10,
    bioload: 4,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: true,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.7,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 25,
    archetype: 'puffer',
    size: 0.75,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#f4efe4',
      belly: '#fbf8f2',
      fin: '#f0c84a',
      pattern: 'stripesV',
      patternColor: '#3a3a44',
      patternScale: 1.0,
      iridescence: 0.2
    },
    habitat: 'Coral and rubble reefs of the Indo-Pacific where it nibbles small critters.',
    facts: [
      'It has four dark saddles across its back like a little pony.',
      'Its skin has a mild poison, so most predators know to leave it alone.',
      'A harmless filefish copies its colors to fool predators into staying away.'
    ],
    care: 'Medium'
  },
  {
    id: 'longhorn_cowfish',
    common: 'Longhorn Cowfish',
    scientific: 'Lactoria cornuta',
    water: 'salt',
    adultSizeCm: 25,
    bioload: 8,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.5,
    schooling: 'solo',
    diet: ['frozen', 'pellet'],
    price: 40,
    archetype: 'boxfish',
    size: 0.9,
    shape: { height: 1.1, finFlow: 1.0 },
    colors: {
      base: '#f0d23a',
      belly: '#f8e070',
      fin: '#e8c828',
      pattern: 'spots',
      patternColor: '#4fb0d8',
      patternScale: 0.8,
      iridescence: 0.25
    },
    habitat: 'Sandy lagoons and seagrass beds of the Indo-Pacific where it blows on the sand.',
    facts: [
      'It has two horns on its head and two on its tail like a tiny yellow cow.',
      'Its body is a hard boxy armor, so it wobbles slowly through the water.',
      'It squirts jets of water at the sand to uncover little critters to eat.'
    ],
    care: 'Hard'
  },
  {
    id: 'yellow_boxfish',
    common: 'Yellow Boxfish',
    scientific: 'Ostracion cubicus',
    water: 'salt',
    adultSizeCm: 25,
    bioload: 8,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 0.5,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'algae'],
    price: 45,
    archetype: 'boxfish',
    size: 0.85,
    shape: { height: 1.15, finFlow: 1.0 },
    colors: {
      base: '#ffd814',
      belly: '#ffe24a',
      fin: '#f0c810',
      pattern: 'spots',
      patternColor: '#2a2a2a',
      patternScale: 1.0,
      iridescence: 0.25
    },
    habitat: 'Coral reefs and lagoons of the Indo-Pacific where it drifts slowly among rocks.',
    facts: [
      'Baby yellow boxfish are bright yellow cubes with black polka dots.',
      'Its body is a stiff bony box, so only its little fins can move.',
      'When it grows up it slowly changes from yellow to blue and brown.'
    ],
    care: 'Hard'
  },
  {
    id: 'lined_seahorse',
    common: 'Lined Seahorse',
    scientific: 'Hippocampus erectus',
    water: 'salt',
    adultSizeCm: 15,
    bioload: 2,
    minSchool: 2,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['expertDiet'],
    zone: 'mid',
    speed: 0.3,
    schooling: 'pair',
    diet: ['frozen'],
    price: 60,
    archetype: 'seahorse',
    size: 1.0,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#c8993a',
      belly: '#d8ad55',
      fin: '#b0842a',
      pattern: 'lateralStripe',
      patternColor: '#f4f0e0',
      patternScale: 1.2,
      iridescence: 0.2
    },
    habitat: 'Seagrass beds and mangroves of the western Atlantic where it clings to plants.',
    facts: [
      'It wraps its curly tail around seagrass so the current cannot sweep it away.',
      'The father carries the babies in a pouch on his belly until they are born.',
      'It has no stomach, so it must sip tiny food almost all day long.'
    ],
    care: 'Hard'
  },
  {
    id: 'blue_devil_damsel',
    common: 'Blue Devil Damsel',
    scientific: 'Chrysiptera cyanea',
    water: 'salt',
    adultSizeCm: 8,
    bioload: 2,
    minSchool: 1,
    temperament: 'aggressive',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.1,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 8,
    archetype: 'clown',
    size: 0.65,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#1560e8',
      belly: '#2f7aff',
      fin: '#0a44c0',
      pattern: 'none',
      patternColor: '#ff8a1a',
      patternScale: 1.0,
      iridescence: 0.6
    },
    habitat: 'Shallow reef flats and lagoons of the Indo-Pacific.',
    facts: [
      'It is an electric neon blue that seems to shine even in dim light.',
      'It is tiny but fierce and will guard its own patch of rock from bigger fish.',
      'In some places the males have a bright orange tail while females are all blue.'
    ],
    care: 'Easy'
  },
  {
    id: 'yellowtail_damsel',
    common: 'Yellowtail Blue Damsel',
    scientific: 'Chrysiptera parasema',
    water: 'salt',
    adultSizeCm: 7,
    bioload: 2,
    minSchool: 1,
    temperament: 'semi',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.05,
    schooling: 'loose',
    diet: ['frozen', 'pellet', 'flake'],
    price: 9,
    archetype: 'clown',
    size: 0.6,
    shape: { height: 1.0, finFlow: 1.0 },
    colors: {
      base: '#1866e0',
      belly: '#2f7cf0',
      fin: '#ffd21a',
      pattern: 'gradientTail',
      patternColor: '#ffd21a',
      patternScale: 1.0,
      iridescence: 0.6
    },
    habitat: 'Coral-rich lagoons of the western Pacific where small groups hover over coral.',
    facts: [
      'Its body is deep blue and its tail is bright sunny yellow.',
      'It is one of the calmest damsels and gets along better than most.',
      'A little group hovers just above the coral, ready to dart in if scared.'
    ],
    care: 'Easy'
  },
  {
    id: 'domino_damsel',
    common: 'Three Spot Domino Damsel',
    scientific: 'Dascyllus trimaculatus',
    water: 'salt',
    adultSizeCm: 12,
    bioload: 4,
    minSchool: 1,
    temperament: 'aggressive',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: ['soloOnly'],
    zone: 'mid',
    speed: 1.0,
    schooling: 'solo',
    diet: ['frozen', 'pellet', 'flake'],
    price: 10,
    archetype: 'clown',
    size: 0.8,
    shape: { height: 1.15, finFlow: 1.0 },
    colors: {
      base: '#17171c',
      belly: '#26262c',
      fin: '#101014',
      pattern: 'spots',
      patternColor: '#ffffff',
      patternScale: 1.3,
      iridescence: 0.2
    },
    habitat: 'Coral reefs of the Indo-Pacific where young ones shelter in anemones.',
    facts: [
      'It is jet black with three white spots like the dots on a domino.',
      'When it is young it can shelter safely inside an anemone like a clownfish.',
      'The white spots fade as it grows, so old ones turn almost all black.'
    ],
    care: 'Easy'
  },
  {
    id: 'talbot_damsel',
    common: 'Talbot\'s Damsel',
    scientific: 'Chrysiptera talboti',
    water: 'salt',
    adultSizeCm: 6,
    bioload: 2,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'mid',
    speed: 1.0,
    schooling: 'loose',
    diet: ['frozen', 'pellet', 'flake'],
    price: 14,
    archetype: 'clown',
    size: 0.6,
    shape: { height: 1.05, finFlow: 1.0 },
    colors: {
      base: '#c8a0d8',
      belly: '#e8c860',
      fin: '#d0a8e0',
      pattern: 'eyespot',
      patternColor: '#1a1a1a',
      patternScale: 1.0,
      iridescence: 0.4
    },
    habitat: 'Reef slopes of the western Pacific where it hovers near the bottom.',
    facts: [
      'It has a soft lavender body with a sunny yellow head.',
      'A black spot sits on its back fin like a fake eye to fool attackers.',
      'It is one of the most peaceful damsels, which is rare for its family.'
    ],
    care: 'Easy'
  },
  {
    id: 'engineer_goby',
    common: 'Engineer Goby',
    scientific: 'Pholidichthys leucotaenia',
    water: 'salt',
    adultSizeCm: 30,
    bioload: 8,
    minSchool: 1,
    temperament: 'peaceful',
    predator: false,
    finNipper: false,
    longFins: false,
    tags: [],
    zone: 'bottom',
    speed: 0.8,
    schooling: 'loose',
    diet: ['frozen', 'pellet'],
    price: 20,
    archetype: 'eel',
    size: 1.1,
    shape: { height: 0.7, finFlow: 1.0 },
    colors: {
      base: '#1a1a22',
      belly: '#2a2a30',
      fin: '#1a1a22',
      pattern: 'lateralStripe',
      patternColor: '#f4f0e0',
      patternScale: 1.6,
      iridescence: 0.15
    },
    habitat: 'Rubble reefs of the western Pacific where it digs a maze of tunnels in the sand.',
    facts: [
      'It digs long tunnels under the rocks, moving sand grain by grain like a builder.',
      'Baby engineer gobies are striped and wriggle in a group to look like a poison sea snake.',
      'As it grows its stripes break into a spotty pattern along its eel-like body.'
    ],
    care: 'Easy'
  }
];
